### ISSUE TITLE
Cannot install package from source (old Rtools)

### ISSUE THREAD

**Issue by dwash7** [florianhartig/DHARMa#116]
I'm having issues installing DHARMa. I'm using Rstudio and I've done every suggestion for trying to install the package, though I have been fruitless: 

> install.packages("DHARMa", dependencies=TRUE, type="source")
WARNING: Rtools is required to build R packages but no version of Rtools compatible with the currently running version of R was found. Note that the following incompatible version(s) of Rtools were found:

  - Rtools 3.3 (installed at c:\Rtools)
  - Rtools 3.4 (installed at c:\Rtools)

Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Erin/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
also installing the dependencies ‘nloptr’, ‘lme4’, ‘glmmTMB’, ‘spaMM’

trying URL 'https://cran.rstudio.com/src/contrib/nloptr_1.2.1.tar.gz'
Content type 'application/x-gzip' length 2448313 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/src/contrib/lme4_1.1-21.tar.gz'
Content type 'application/x-gzip' length 4124154 bytes (3.9 MB)
downloaded 3.9 MB

trying URL 'https://cran.rstudio.com/src/contrib/glmmTMB_0.2.3.tar.gz'
Content type 'application/x-gzip' length 1750823 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/src/contrib/spaMM_3.0.0.tar.gz'
Content type 'application/x-gzip' length 1044448 bytes (1019 KB)
downloaded 1019 KB

trying URL 'https://cran.rstudio.com/src/contrib/DHARMa_0.2.4.tar.gz'
Content type 'application/x-gzip' length 4047330 bytes (3.9 MB)
downloaded 3.9 MB

* installing *source* package 'nloptr' ...
** package 'nloptr' successfully unpacked and MD5 sums checked
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG          -O2 -Wall  -mtune=generic -c dummy.cpp -o dummy.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG       -I"/i386/include"   -O3 -Wall  -std=gnu99 -mtune=generic -c init_nloptr.c -o init_nloptr.o
init_nloptr.c:35:19: fatal error: nlopt.h: No such file or directory
 #include "nlopt.h"
                   ^
compilation terminated.
make: *** [init_nloptr.o] Error 1
ERROR: compilation failed for package 'nloptr'
* removing 'C:/Users/Erin/Documents/R/win-library/3.6/nloptr'
Warning in install.packages :
  installation of package ‘nloptr’ had non-zero exit status
ERROR: dependency 'nloptr' is not available for package 'lme4'
* removing 'C:/Users/Erin/Documents/R/win-library/3.6/lme4'
Warning in install.packages :
  installation of package ‘lme4’ had non-zero exit status
ERROR: dependency 'nloptr' is not available for package 'spaMM'
* removing 'C:/Users/Erin/Documents/R/win-library/3.6/spaMM'
Warning in install.packages :
  installation of package ‘spaMM’ had non-zero exit status
ERROR: dependency 'lme4' is not available for package 'glmmTMB'
* removing 'C:/Users/Erin/Documents/R/win-library/3.6/glmmTMB'
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status
ERROR: dependencies 'lme4', 'glmmTMB', 'spaMM' are not available for package 'DHARMa'
* removing 'C:/Users/Erin/Documents/R/win-library/3.6/DHARMa'
Warning in install.packages :
  installation of package ‘DHARMa’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Erin\AppData\Local\Temp\Rtmp6P6tuv\downloaded_packages’

> library("DHARMa")
Error in library("DHARMa") : there is no package called ‘DHARMa’

**Comment by florianhartig** [comment]
It looks as if you're on a Windows computer, and you're trying to install packages from source (type="source")).

It seems some dependences included C code, and under Windows, R is using the compiler included in Rtools for that. Seems your Rtools is outdated, install the latest version via https://cran.r-project.org/bin/windows/Rtools/

That being said - there is absolutely no reason for a standard user to install from source, just install DHARMa normally via 

`install.packages("DHARMa")`

**Comment by dwash7** [comment]
You were right - updating rtools allowed me to download it via CRAN. I was only downloading by a source because nothing else was working. Thanks for the input and I look forward to using your package.

**Comment by florianhartig** [comment]
Good that it works for you.

Just out of curiosity - the standard command install.packages("DHARMa") didn't work? Do you remember the error message, or could you paste it here? Also, could you print out a session.info() so that I can see what system you are working on?

**Comment by dwash7** [comment]
@florianhartig, sorry, I don't have the error message or session information anymore as I had reboot.  The error message was more or less along the lines of not being able to find the package to install. I had to install the newest version of R and Rstudio and Rtools, but here is my current session info:

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.3 MuMIn_1.43.6  lme4_1.1-21   Matrix_1.2-17 MASS_7.3-51.4 DHARMa_0.2.4 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         TMB_1.7.15         splines_3.6.1      lattice_0.20-38    foreach_1.4.4     
 [6] minqa_1.2.4        pbapply_1.4-1      tools_3.6.1        parallel_3.6.1     grid_3.6.1        
[11] spaMM_3.0.0        nlme_3.1-140       iterators_1.0.10   qrnn_2.0.4         nloptr_1.2.1      
[16] codetools_0.2-16   gap_1.2.1          proxy_0.4-23       compiler_3.6.1     boot_1.3-22       
[21] stats4_3.6.1       GLMMadaptive_0.6-0

**Comment by florianhartig** [comment]
ok, but then I assume now install.packages("DHARMa") would probably also work, right? Never mind, thanks for the info!

**Comment by dwash7** [comment]
@florianhartig yes, install.packages("DHARMa") works properly now with all the updates. Thanks!
