### ISSUE TITLE
testSpatialAutocorrelation() error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by carinamina** [florianhartig/DHARMa#119]
Hi, I was happy to find the spatial autocorrelation test in DHARMa. I have replicate observations per sessile individual, and it's great that I can use the recalculateResiduals function to group by individual, and I don't have to run totally different models on individual means to test for spatial autocorrelation.

However, I am running into an error I don't understand, even when I try to do the simplest check of `testSpatialAutocorrelation(resid_indiv)` where `resid_indiv` is a vector of 75 numbers. It returns `Error: $ operator is invalid for atomic vectors.` I don't get this because there is no $, at least on the surface!

`lr11 <- read.csv("https://raw.githubusercontent.com/carinamina/snapdragon-pollination/master/lr11.csv", header = TRUE)`
`display <- glmer(visit ~ flowers_per_spike + (1 | id/survey/spike), family = binomial(link = "logit"), data = lr11)`
`simulationOutput <- simulateResiduals(fittedModel = display, n = 250)`
`plot(simulationOutput)`
`resid_indiv <- recalculateResiduals(simulationOutput, group = lr11$id)$scaledResiduals`
`x_indiv <- as.vector(unique(lr11$eastC))`
`y_indiv <- as.vector(unique(lr11$northC))`
`testSpatialAutocorrelation(resid_indiv, x = x_indiv, y= y_indiv)`
note: same error if the x and y aren't included.

While I'm here, I was also wondering how I can check or guarantee that the residuals, x, and y point to the same individuals. I couldn't find any way in the DHARMa object to check ID.

Thank you!

**Comment by florianhartig** [comment]
The first argument in testSpatialAutocorrelation must be a DHARMa output, not the scaled residuals. Thus, remove $scaledResiduals

**Comment by florianhartig** [comment]
p.s.: using as.vector(unique(lr11$eastC)) assumes that lr11$eastC is ordered according to lr11$id, I hope that this is the case.

**Comment by carinamina** [comment]
Ah! So easy! Thank you for the quick response. That fixed it.

Ok, so my x and y should be sorted alphabetically by id, to match what recalculateResiduals is doing?

**Comment by carinamina** [comment]
They are. Thanks for the check!

**Comment by florianhartig** [comment]
Yes, the recalculateResiduals functions calculates new residuals, one residual per group.

x and y values should be per group, i.e. in the same order as the group variable. 

Glad that this helped.
