### ISSUE TITLE
Unexpected wave in residual plots

### ISSUE THREAD

**Issue by gweelia** [florianhartig/DHARMa#122]
Hello,

I used DHARMa recently in a project where I created zero-inflated NB1, NB2, and Poisson models with glmmTMB. I used glmmTMB to model death counts in boroughs of London across five years, with more than 6000 datapoints used to fit each model. The models had a few predictors (age [continuous], sex, socioeconomic status [continuous]) plus a random effect for the 32 boroughs, with the zero-inflated component modelled on age.

First, thank you, because I  really struggled to find any packages compatible with glmmTMB objects, and this one saved me!

When I was exploring the fit of my models, the residual plots often showed a backwards-S wave/diagonal pattern, like this one:
![fig9](https://user-images.githubusercontent.com/55252740/64807243-b7f5fc80-d58c-11e9-8257-f75dadc01d68.png)
The pattern always appeared the same way; it mostly varied in terms of where along the x-axis it appeared, sometimes appearing further to the right (ie, for higher predicted values). 

In the DHARMa guides, there's mention of a diagonal pattern in the residuals when dealing with random effects, but from bottom left to top right, so this didn't seem to be it.

It also didn't seem to be dependent on the model type (ie, NB or Poisson) and could still appear for models that showed good fit on the Q-Q plot (eg, with no outliers as in the above example).

I've been trying to work out what it is or is indicating, but conceptually I'm struggling as my background is fairly weak. Hoping that you might be able to point me in the right direction...!

**Comment by florianhartig** [comment]
Hi gweelia,

I've never seen this pattern, but it looks as if there is a particular values in your data that is more likely, and before that a value that doesn't appear, as if every 5 would have been transformed into a 6 or so. Another option that I could imagine is that you have used discrete predictors for the zero-inflation, and this somehow doesn't fit. 

If you want, you can send me the data / model via email (if you don't want to post it here), then I can have a look. 

Best,
Florian

**Comment by gweelia** [comment]
Hi Florian,

That's very helpful, thank you. A peculiarity of the dataset is that it rounded any death counts <5 to either 0 or 5, to protect the anonymity of the populations considered, so there are no death counts in the data of 1, 2, 3, or 4! The position of the curve makes me wonder whether this is what we're seeing, however, given that the range of the data is much higher than 4 (eg, in the example below, we have counts from 0 to 75). As for zero-inflation predictors, some models have both age (continuous) and sex included in the zero-inflation component, but display the wave pattern regardless of whether one or both of those predictors are included. 

I've uploaded the dataset here (it's open access), if you still want to play with it...! The data were provided with age categories, and the continuous age variable was obtained with midpoints of categories/a bit of guesstimating. Separate models were run for each of the causes of death listed (eg, cerebrovascular diseases in the code below).

[clean dataset - final.zip](https://github.com/florianhartig/DHARMa/files/3612948/clean.dataset.-.final.zip)

Below is the code for the cerebrovascular diseases model, which displayed a wave with `Age_cont` or `Age_cont + Sex` in the zero-inflation model.

`library(DHARMa)`
`library(glmmTMB)`

`df0 <- read.csv("clean dataset - final.csv")`
`cereb.final <- glmmTMB(Cerebrovascular ~ IMD_score + Age_cont + Sex + offset(log(Population)) + (1|Area), 
                       ziformula = ~ Age_cont + Sex, 
                       family=nbinom2, data=df0)`

`cereb.res <- simulateResiduals(cereb.final)`
`plot(cereb.res, quantreg = T)`

I had plotted the residuals _vs_ predictors but, again, I can't say they spoke much to me (my ignorance is really shining through).

![Residuals vs predictors](https://user-images.githubusercontent.com/55252740/64911361-b8230300-d718-11e9-8413-38fe0894885e.png)

I'm giving a presentation on this analysis for my MSc on Friday, which is why I'm curious to understand what I saw in case any of the professors interrogate me on it, but it really isn't urgent if you have nicer things to do with your time!

Thanks again,
Giulia

**Comment by florianhartig** [comment]
Hi Giulia,

> rounded any death counts <5 to either 0 or 5

I can check later, but I guess it's pretty obvious that this is the problem, as this doesn't fit to the assumption of a zero-inflated Poisson (which would expect values between 1-4 as well). What you have here is a kind of special censoring, where your data <5 is not completely missing, but partly masked (because zero is not the correct value).

I think you have 2 options:

- keep your model as it is, and accept that you don't really have a perfect model for your data (you could show with simulations (i.e. create data and do this <5 rounding by hand) that the inference (= ability to recover parameter estimates) is still acceptable

- try to find a more appropriate model that takes care of this problem. The simplest option might be to remove the zeros, and fit a censored model to the >5 data only, and fit the zeros alone. The best option would probably be to write a likelihood for the way the data was created, with the <5 masking, but this is probably only possible if you define the likelihood by yourself, e.g. in Jags, Stan, or in the BayesianTools package that I maintain.
