### ISSUE TITLE
lme4:::simulate.merMod fails for inverse gausiam GLMM 

### ISSUE THREAD

**Issue by nahorp** [florianhartig/DHARMa#125]
Hello :)

Firstly, thank you for a great package and very clear documentation with examples, it is really appreciated.

 I am running a GLMM (with the `glmer` function from lme4) using an inverse gaussian distribution and trying to calculate the scaled residuals (with the `scaledResiduals` function). However, the following error comes up,

```
Error in sfun(object, nsim = 1, ftd = rep_len(musim, n * nsim), wts = weights) : 
  could not find function "sfun"
```
Below is a reproducible example that should output the same error,

```
# Loading packages

library(statmod)
library(lme4)
library(DHARMa)

# Creating data

set.seed(666)

id <- factor(1:20)
a <- factor(rep(c("a1","a2"),each=5000/2))
b <- factor(rep(c("b1","b2"),each=5000/2))
y <- rinvgauss(5000, 1, 2)
df <- data.frame(id=id,
                 x1=sample(a),
                 x2=sample(b),
                 y=y)

# Fitting model

model_fit <- glmer(y ~ x1 * x2 
                   + (1|id),
                   family = inverse.gaussian(link = "inverse"),
                   control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)),
                   data = df)

# Calculate scaled residuals

simuationOutput <- simulateResiduals(fittedModel = model_fit, n = 250)
```
I do not know enough to know if this is related or not but I get the same error when using the `method = "PB"` argument (parametric bootstrapping) while fitting a model with the `mixed` function from the afex package (singmann/afex#74) and as far as I know DHARMa simulates by bootstrapping as well.

**Comment by florianhartig** [comment]
Hi nahorp,

yes, the errors in DHARMa and afex are related, because the issue seems to be in lme4, more specifically in

`lme4:::simulate.merMod(model_fit)`

which is used by DHARMa and probably also by all packages that implement a parametric bootstrap. Looking at your example, I don't really see a reason why this shouldn't work, so I suppose it's a bug.

I can't do anything about this from the DHARMa side, but will create an issue for the lme4 team.

Best,
Florian

**Comment by nahorp** [comment]
Hi Florian,

Thank you for your reply and for the additional insight about where the problem may lie as well as referencing it to the lme4 team.

Hopefully, it is a relatively easy fix :0

Cheers,

Rohan

**Comment by nahorp** [comment]
This now works, in the development version from Github, via the fix at https://github.com/lme4/lme4/commit/59c50fb5b2aa07611646c01f13f1de1fb75ebcdc. Thank you!

**Comment by nahorp** [comment]
This now works, in the development version of `lme4` from Github, via the fix at https://github.com/lme4/lme4/commit/59c50fb5b2aa07611646c01f13f1de1fb75ebcdc. Thank you!
