### ISSUE TITLE
Interpreting Residual Plots for Binomial GLMM—Overdispersion and Zero Inflation

### ISSUE THREAD

**Issue by Chughes3** [florianhartig/DHARMa#128]
Hello,

I'm new to GitHub, so I apologize if this isn't the right place for this type of question.

I'm using the DHARMa package to help evaluate the residuals of a binomial glmm. I have obtained the following plots for my residuals: 

![Screen Shot 2019-11-23 at 1 18 16 PM](https://user-images.githubusercontent.com/58117799/69483312-c154de00-0df3-11ea-8676-c8dbff79bd11.png)

These plots looked really good to me, so  I was surprised to get a significant result from the dispersion test (plot below). 

![Screen Shot 2019-11-23 at 1 28 49 PM](https://user-images.githubusercontent.com/58117799/69483423-4e4c6700-0df5-11ea-8bbf-ea36a8a4539c.png)

From reading the DHARMa vignette, I thought that any overdispersion in the model would be apparent in the QQ residual plot. Is there a reason for the seeming discrepancy between the QQ plot and the results of the dispersion test? My model also appears to be zero inflated (plot below).

![Screen Shot 2019-11-23 at 1 29 07 PM](https://user-images.githubusercontent.com/58117799/69483425-53a9b180-0df5-11ea-89ca-0bb7c4242621.png)

Do you have any thoughts on what might be going wrong here? Does my model seem to be properly specified? If the overdispersion is not showing up in the original plot, is it a problem for the model that the official dispersion test is significant?

If more information about is helpful, the model is: 
Model<-glmer(behaviorprop~AvgTemp+CoverType+Temp*CoverType+(date|Individual), data=behavior, family=binomial, weights=WeightingFactor)

Thank you for any guidance you may be able to provide!

**Comment by florianhartig** [comment]
Hi Chughes3,

I assume you are fitting k/n data, where behaviorprop  is k, and the variable WeightingFactor is n, is that correct? 

About your fit - yes, it looks broadly good, but note that also your outlier test in the overview plot seems significant. What I suspect is that the central quartiles of the residual distribution are OK, but then we find more than expected values in the far tail of the distribution (or outside the simulation envelope = outliers). 

About what to do - the overdispersion is not enormous. The zero-inflation looks more odd to me. I would plot residuals against all predictors and see if you see obvious problems. In general, the idea of a residual test is to give you ideas about how to improve the model, and identify gross errors, not to find a model with "perfect residuals".

Side note: what's the idea of fitting (date|Individual)? Do you mean (1|date/individual)?

**Comment by Chughes3** [comment]
Hi Florian,

Thanks for your help. Yes, you're correct—I am fitting k/n data with behaviorprop as k and WeightingFactor as n. 

About the structure of the RE: because I have data from each site from multiple successive days, I was worried about temporal autocorrelation between dates for each individual. A colleague who has more experience with mixed effects models than I do suggested that structuring the random effect as (date|individual) would help account for any temporal autocorrelation. I have since restructured the model according to your suggestion for the random effect (1|date/individual), and things have improved a bit (the outlier and overdispersion tests no longer return significant p-values); however the zero inflation is still very significant (plots below).

![Screen Shot 2019-11-24 at 11 17 58 PM](https://user-images.githubusercontent.com/58117799/69512213-27835300-0f11-11ea-875a-f673ab29f8b9.png)

![Screen Shot 2019-11-24 at 11 18 29 PM](https://user-images.githubusercontent.com/58117799/69512208-23573580-0f11-11ea-8c66-47ddc9d1bbae.png)

![Screen Shot 2019-11-24 at 11 18 52 PM](https://user-images.githubusercontent.com/58117799/69512192-11759280-0f11-11ea-9db7-3097e976b86c.png)

I took your suggestion and plotted the residuals against the predictors used in the model. I don't notice any major issues here. Do you notice any obvious problems that I'm missing? 

![Screen Shot 2019-11-24 at 11 24 39 PM](https://user-images.githubusercontent.com/58117799/69512774-58fd1e00-0f13-11ea-9f8f-b8e8c7c524b5.png)

![Screen Shot 2019-11-24 at 11 25 05 PM](https://user-images.githubusercontent.com/58117799/69512765-4c78c580-0f13-11ea-9a79-a2aba4493f38.png)


Thank you again for taking the time to answer!
-Caroline

**Comment by florianhartig** [comment]
Hi Caroline,

about the random effect: from your comment, it sounds as if you should read a bit about the lme4 syntax for RE specification. A nested RE of the form (1|date/individual) fits a separate random effect for each individual and date. If you want to take out effects of individuals and date, but assume that the individual effect is constant across time, you should fit crossed (1|date) + (1|year). There's no right or wrong, it's just about translating the assumptions that you want to make correctly into a model. 

The fact that the residuals fit better now says nothing about whether this is the right RE structure. The RE structure should be decided upon based on the structure of your data. If the residuals don't fit, you can correct this with other measures.

Let's assume you stay with (1|date/individual) - yes, your plots look fine, except for this bit of zero-inflation. I don't think it's a major issue for the inference, but if you want to address it, you could move to glmmTMB, where you can add a zero-inflation term. The thing is that you probably also have one-inflation (you can check for this in DHARMa), which will then be difficult to correct simultaneously. I would probably leave it like it is.

**Comment by Chughes3** [comment]
Hi Florian,

It sounds like I was misunderstanding the random effects syntax. I'll do some more reading up to try and figure out what works best for the questions I'm asking.

I really appreciate your advice. Thank you!

Best,
Caroline
