### ISSUE TITLE
recalculateResiduals error: arguments must have same length 

### ISSUE THREAD

**Issue by fkalbe** [florianhartig/DHARMa#133]
Hi,

I'm trying to use the recalculateResiduals function on my binomial glmer (lme4) model that includes a random intercept + slope per participant of an experiment, as well as a random intercept per picture that was presented within this experiment. I'd like to add the participant id ("subj") as a grouping factor like so:

```R
simulationOutput <- simulateResiduals(fittedModel = example_model, n = 250)
simulationOutput <- recalculateResiduals(simulationOutput, group = df$subj)
```

However, this throws the following error that is passed from ``aggregate.data.frame()``:

```
Error in aggregate.data.frame(as.data.frame(x), ...) : 
  arguments must have same length
```

Intially, I though that the issue might be that ``df$subj`` had a different length that the data that was used to fit the model. However, I'm fairly certain now that they are the same length and the problem persists. Any ideas how to troubleshoot this? Thanks!

**Comment by florianhartig** [comment]
Hi,

the reason is probably that you have NA in your data frame, which means that R will remove those rows from the data before fitting them in the regression. I'm currently not checking for this explicitly, not sure if this would be even possible without forcing changing na.action (which is very inconvenient for the user)

In any case, check for NA and if you have NAs in your data, try to remove those via data[complete.cases(data), ]

**Comment by fkalbe** [comment]
Thanks for your quick response. Here's how I'm fitting the model:

```R
example_model <- glmer(hit ~ 
                       predictor
                     + (1 + predictor | subj) 
                     + (1 | imgID)
                     ,family = binomial(link = "logit")
                     ,data = filter(df, !is.na(predictor)))
```

and the following call to ``recalculateResiduals()``:
```R
simulationOutput <- simulateResiduals(fittedModel = example_model , n = 250)
simulationOutput <- recalculateResiduals(simulationOutput, group = df$subj[!is.na(df$predictor)])
```

So to me it seems like I'm already filtering NAs oder did I miss something?

**Comment by florianhartig** [comment]
!is.na(predictor) is not considering NAs in the response. The usual way is to use complete.cases(data). 

As an alternative: check if your simulationOutput$scaledResiduals has the same length as df$subj[!is.na(df$predictor)]

**Comment by fkalbe** [comment]
Yep, that was it, there were additional NAs in the response variable that I forgot about. Thanks again, I'm closing the issue.
