### ISSUE TITLE
Questions about testing spatial autocorrelation

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#141]
From a user: 

> 
> 1) I have duplicate locations and according to the guidance in the  DHARMa documentation, I need to use recalculateResiduals and aggregate them by mean before testing for spatial autocorrelation. I, therefore, use:
> 
> ```
> simulationOutputAgg <- recalculateResiduals(simulationOutput, group =paste(mydata$latitude, mydata$longitude),  aggregateBy = mean)
> 
> This doesn’t work. It throws the error: 
> 
> Error in aggregate.data.frame(as.data.frame(x), ...) :
> 
>   arguments must have same length
> 
> Calls: <Anonymous> ... aggregate -> aggregate.default -> aggregate.data.frame
> 
> Execution halted
> ```
> 
> This surprises me because my lon and lat have the same length. Would you please advise if there is a work-around this problem?
> 
> 2) I cannot seem to find examples in the DHARMa documentation of how to actually remove/account for spatial autocorrelation after testing. I, therefore, turn to the `spaMM` package and add Matern to my model. This works fine; unfortunately, the results do not give P-Values. I have read that some researchers do not consider P-Values to be reliable, but I do really need to get them. I have tried sjstats::p_value(my_model) and lmerTest::as_lmerModLmerTest but they both don’t seem to recognise the fitme() model structure of spaMM.
> 
> Kindly, is my understanding that DHARMa is only for diagnostics correct or does it provide the ability to add a spatial autocorrelation structure? If it doesn’t are you in a position to advise how I can get P-Values when using spaMM?

**Comment by florianhartig** [comment]
Hi,

1) in principle this should work ... there must be something wrong with your data. Probably you have NA in your data. See https://github.com/florianhartig/DHARMa/issues/133 . I should throw a warning for this. 

2) No, DHARMa only diagnoses. There are a number of packages that can fit spatial models, including spaMM and glmmTMB. glmmTMB will give p-values (on the normal regression coefficients). You will have to ask the developer of spaMM about p-values, I'm not sure if it's possible to get them. 

Note that after fittings such spatial models, you will still have spatially autocorrelated residuals, just that their effect is accounted for when fitting the model. But if you check a spatial glmmTMB model with DHARMa, you will still see a spatial pattern in the residuals. This is normal.

**Comment by JNayo** [comment]
Yes, the data had some NA values. Thanks for referring me to [#133 ](https://github.com/florianhartig/DHARMa/issues/133)
