### ISSUE TITLE
weights argument causes overdispersion in glmmTMB beta regession

### ISSUE THREAD

**Issue by Pet0rvL** [florianhartig/DHARMa#146]
Hi Florian,

Many thanks for your help on this so far, I really appreciate it. Having discussed dispersion parameters on GLMM beta models on Cross Validated, I would like to show you this particular case. I am running an analysis on the effect of canopy cover (`OverheadCover`) and the number of carcasses placed on the same location (`CarcassNumber`) on the proportion of carrion eaten by birds (`ProportionBirdsScavenging`). These data points were collected at different national parks, so Area is included as a random factor. The `summary` output gives me an overdispersion parameter of 25.1 and `DHARMa::testDispersion` tells me there is indeed overdispersion present (`p-value < 2.2e-16`). The response data (`ProportionBirdsScavenging`) is transformed to exclude true 0's and 1's, so it couldn't be a case of zero or one inflation, right? 

Is there a way of fixing this overdispersion besides the zero or one inflation turned on? You explained before that sometimes, even with zero-inflation, dispersion for the beta doesn't fit. Would that be the case here?

If you want to explore the data, I've provided some code to reconstruct. 

```
rm(list = ls())
library(glmmTMB)
library(DHARMa)

df <- data.frame(ProportionBirdsScavenging = c(0.406192519926425, 0.871428571428571, 0.452995391705069, 0.484821428571429, 0.795866569978245, 0.985714285714286, 0.208571428571429, 0.573982970671712, 0.694285714285714, 0.930204081632653, 0.0483709273182957, 0.0142857142857143, 0.661904761904762, 0.985714285714286, 0.0142857142857143, 0.0142857142857143),
                      pointWeight = c(233, 17, 341, 128, 394, 46, 5, 302, 10, 35, 57, 39, 12, 229, 28, 116),
                      OverheadCover = c(0.671, 0.04, 0.46, 0.65, 0.02, 0, 0.8975, 0.585, 0.6795, 0.0418, 0.5995, 0.6545, 0.02, 0, 0.92, 0.585),
                      CarcassNumber = as.factor(c(1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2)),
                      Area = c("Hamert", "KempenBroek", "KempenBroek", "KempenBroek", "Markiezaat", "Markiezaat", "Meinweg", "Valkenhorst", "Hamert", "KempenBroek", "KempenBroek", "KempenBroek", "Markiezaat", "Markiezaat", "Meinweg", "Valkenhorst"))
df$pointWeight_scaled <- scales::rescale(df$pointWeight, to = c(0.0001,1)) # rescale weights

glmm_interaction <- glmmTMB(ProportionBirdsScavenging ~ OverheadCover * CarcassNumber + (1|Area), data = df, beta_family(link = "logit"), weights = pointWeight_scaled)
summary(glmm_interaction)
res <- simulateResiduals(glmm_interaction, plot = T)
testDispersion(res)

# this is how it looks
plot(ggeffects::ggpredict(glmm_interaction, terms = c("OverheadCover [0:1 by=.005]", "CarcassNumber"), ci.lvl = 0.682))
```

**Comment by florianhartig** [comment]
Hi Pet0rvL,

thanks for bringing this to my attention - it seems that this is a bug, and the problem arises because you are using weights for the fit. If you fit the model without weights, there is no problem. 

The problem arises because the weights affect the model fit (and dispersion estimate), but there is no clear way to simulate data from a glm with weights, so most packages (including glmmTMB) seem to simply ignore the weights in the simulation. In this case, it can look to DHARMa as if there is a misfit.

I had already an issue open about this https://github.com/florianhartig/DHARMa/issues/7 , but I hadn't realised how consequential the problem is - DHARMa should definitely warn the user that models with weights can't be reliably diagnosed - I will implement this in the next release.

For your specific case, the conclusion is basically that you can't use the tests as long as you have weights. Can I ask how you derive these weights in the first place?

Best,
Florian

**Comment by Pet0rvL** [comment]
Hi,

Good to know. The weights are based on the number of scavengers who ate from the carrion. 
I would like to run the analysis without the weights so that DHARMa would work, but then a proportion based on 15 animals would count as heavy as a proportion based on 600. (Yes, the differences are this large.) I had problems with my weights before and rescaled them to mitigate their effect, so that `glmmTMB` would not force a line through the heavily weighted data points and always result in a spuriously significant p-value (even with randomly generated data).

As you correctly mention above, if I run the `glmmTMB` without a weights argument, the dispersion parameter of the `summary` output is 4.75 (instead of 25.1) and `DHARMa` tells me there is no overdispersion. Long story short, as I understand (because I need my wieghts) there is no real way of  examining whether my model is overdispersed?

For now, do you think that (without truly knowing), I can simply report that considering models which specify a Beta distribution estimate the dispersion, the overdispersion parameter in the `summary` output should not be an issue of concern.

Thanks!

Peter

**Comment by florianhartig** [comment]
Hi Peter,

yes, as I wrote on CV, a model with a dispersion parameter cannot be overdispersed per definition, so there is no need to test this specifically. A significant overdispersion test in such a model would rather point to a different problem, e.g. that the distribution doesn't fit. 

That being said - when I understand correctly what you are doing, you have k/n observations, fit with a beta, and weight according to n. If so, this is a binomial problem, so why don't you just fit a binomial? This seems much nor natural, and takes care of the weighting automatically. I'm also not 100% positive that the likelihood should be weighted linear with n in the beta if you have binomial-type data, my feeling would be that it's probably sqrt(n), but I would have to check this. Anyway, you could fit

```
df$BirdsScavenging = round(df$pointWeight * df$ProportionBirdsScavenging)

fit <- glmmTMB(cbind(BirdsScavenging , pointWeight - BirdsScavenging) ~ OverheadCover * CarcassNumber + (1|Area) , data = df, family = binomial)
summary(fit)
res <- simulateResiduals(fit, plot = T)
testDispersion(res)
```

When I did this, the outlier test was significant (might not happen for you, depends on the random seed), but I think you can disregard this, there are very few outliers and to me the fit looks fine, it's quite a complex model for the number of data points anyway.

**Comment by Pet0rvL** [comment]
Hi Florian,

Thanks for thinking along with me. First of all, excuse me for my inexperience. Could you elaborate what you mean with k/n observations? If I understand you correctly, you calculate the absolute number of birds scavenging on the carcasses, and then column combine with the rest of the animals (in this case mammals). What does it mean to have the absolute numbers of both birds and mammals as response variable (combined via `cbind`), in stead of only the manually calculated proportion of birds as response and adding weights separately (as I've done). 

When analysing continuous proportional data (`OverheadCover` % on `ProportionOfBirds` %), a binomial does not do the job, right? At least that is what I understand. But with this technique of `cbind` multiple absolute values as response, a beta is not necessary anymore?

Sorry to bother you with these questions, my original question regarding overdispension in beta `glmmTMB` is answered. I'm just amazed with all the possibilities in statistics and R and I'm eager to learn more.

**Comment by florianhartig** [comment]
Hi Peter,

I don't know your data, but if you have a situation where you have n birds, and k of them do something, you don't have continuous proportions, you have discrete (= binomial) proportions, i.e. a binomial model, see e.g. https://online.stat.psu.edu/stat504/node/225/

Beta regression is only appropriate where you have true continuous proportions.

**Comment by Pet0rvL** [comment]
This is a much more straightforward analysis. Thanks for your help, that explains a lot.

**Comment by florianhartig** [comment]
OK, great. Noted that k/n logistic regressions, unlike 1/0, can be overdispersed, because the binomial has fixed dispersion, so you should test them and could move to a beta-binomial if needed. But when I tried your data, I didn't see overdispersion. There is a further section in the vignette on testing binomial data.
