### ISSUE TITLE
No red smoother for continuous preds in res vs pred plots

### ISSUE THREAD

**Issue by SUsvy** [florianhartig/DHARMa#150]
I'm running a negative binomial glmmTMB model with multiple predictors. When I use the `simulateResiduals` function to diagnose the model and plot the simulated residuals against predictors, most of my continuous variables have the red smoother plotted (and correctly matching the solid line). The categorical variables are plotted as boxplots and it's fine. However, a couple of continuous predictors don't have the smoother plotted. These two have a high occurrence of the same value (0) - are they being treated somehow differently by DHARMa?

Here's a plot of some of the predictors, showing 2 correct continuous vars, 2 correct categorical ones, and 2 incorrect continuous ones (on the bottom).  

Edit - hmm. When I add quantreg = T to the `plotResiduals`, I get the full plot. I guess that works as a workaround?

![image](https://user-images.githubusercontent.com/18539372/77580449-cf5a5e80-6eba-11ea-8566-15e2d65fb61c.png)

**Comment by florianhartig** [comment]
Hi SUsvy, 

this is expected behavior - see help, the relevant parameter here is asFactor, the help states that: 

> should the predictor variable be treated as a factor. Default is to choose this for <10 unique predictions, as long as enough predictions are available to draw a boxplot.

You can overwrite this, but the quantile plots often don't work if you have only 3 values on the x axis, therefore the default.

Best,
Florian

**Comment by SUsvy** [comment]
Sorry, I'm not following - the ones I have issues with have a continuous x axis, with many more than 3 (or 10) values (they're the 2 plots on the very bottom of the stack).

**Comment by florianhartig** [comment]
Sorry, I misread which plots you mean (completely my fault, it was written quite clearly). 

You seem to have > 2000 points, so the function will try to use the loess smoother, to improve speed. If the line is not plotted, the calculation apparently crashes. Yes, I too suspect that this vertical line is the reason, with all values at the same point. 

I'm not sure if there is much that I can do about this, it's clear that functions like quantile regressions or smoother can crash in particular situations, if there is a very weird distribution of points. 

If the quantile regression works or you, I think it's fine. I don't think there is a fundamental problem underlying, it's just a problem of the plot function.

**Comment by SUsvy** [comment]
Sounds good, and thank you for the response! I can definitely live with it, especially considering that I discovered the quantreg switch while posting the original question.

**Comment by florianhartig** [comment]
Great. btw, the development version of DHARMa (which, however, still has a few smaller bugs, but should probably work for you) has a new, much faster quantreg. I urgently need to fix the bugs to roll this out, but it might already work for you (these are all compatibility bugs, nothing functional, so if it runs for you, it's fine). 

Note the changed syntax for plotResiduals though.
