### ISSUE TITLE
Support for glmmTMB in DHARMa

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#16]
A user requested support for https://github.com/glmmTMB/glmmTMB 

## Status of this request (updated)

* glmmTMB is supported by DHARMA since https://github.com/florianhartig/DHARMa/releases/tag/v0.1.6.2. 

* glmmTMB is fully supported (fixing the re.form problem and some other things, see below) since DHARMa 0.2.7 and glmmTMB 1.0

A simple example is

```
m <- glmmTMB(count~ mined, family=poisson, data=Salamanders)
summary(m)

res = simulateResiduals(m)
plot(res, asFactor = T)
```

![image](https://user-images.githubusercontent.com/5457753/38135847-b9be316e-341a-11e8-8e46-ab9e32451d09.png)

More examples in the vignette or in https://github.com/florianhartig/DHARMa/tree/master/Code/DHARMaPackageSupport/glmmTMB

**Comment by florianhartig** [comment]
it seems glmmTMB has now implemented a simulate function, so I will add it to DHARMa https://cran.r-project.org/web/packages/glmmTMB/vignettes/sim.html

In the meantime, you can use the interim solution above, skipping the step to implement the simulate function yourself

**Comment by florianhartig** [comment]
OK, I have a test version that seems to work more or less in branch glmmTMB

```
devtools::install_github(repo = "florianhartig/DHARMa", subdir = "DHARMa", 
ref = "glmmTMB", dependencies = F, build_vignettes = T)
```

adjust dependencies = F, build_vignettes = T depending your system / desires. 

Note: I had problems with the CRAN version of glmmTMB (crashed with some models). I would therefore recommend installing the development version. 

Current limitations of glmmTMB

* residual function doesn't work with factor response (bug)
* pearson residuals don't work with zi terms (not implemented), which limits some of the overdispersion tests
* Currently, glmmTMB doesn't support the reform argument. 
  * predict() is conditional on all random effects, corresponding to lme4 re.form = NULL
  * simulate() is unconditional, i.e. all random effects will be resimulated, corresponding to lme4 re.form = 0
  * That means that all predictions and simulations are conditional on REs, which can sometimes create a positive correlation between res and predicted , see https://github.com/florianhartig/DHARMa/issues/43

**Comment by florianhartig** [comment]
Merged into master with https://github.com/florianhartig/DHARMa/commit/ed836ddb296905a26ff9f61b4eb7a316d2744203

**Comment by florianhartig** [comment]
Things to check before closing

* glmmTMB residual function with factor response
* pearson residuals don't work with zi terms (not implemented), which limits some of the overdispersion tests (probably not a real problem, see https://github.com/glmmTMB/glmmTMB/issues/313)
* Structured RE behavior

**Comment by florianhartig** [comment]
added instructions about how to calculate unconditional predictions by hand

**Comment by mebrooks** [comment]
Any chance you could test the `re.form` in `predict` sometime soon? Will this resolve the warning from `simulateResiduals` which refers to this issue?

**Comment by florianhartig** [comment]
Hi Mollie, yes, I have tested this in https://github.com/florianhartig/DHARMa/tree/2.4.2-glmmTMBfix and it works like a charm, at least as far as the integration in DHARMa and the problem I had with https://github.com/florianhartig/DHARMa/issues/16 is concerned. As soon as you push this on CRAN, I will do an update to DHARMa!

**Comment by florianhartig** [comment]
Notes to users: if you want to make use of these recent changes

- install glmmTMB from GitHub
- install https://github.com/florianhartig/DHARMa/tree/2.4.2-glmmTMBfix from GitHub (this is the DHARMa branch which fits to the updated glmmTMB)

**Comment by florianhartig** [comment]
Reform problem is fixed with https://github.com/florianhartig/DHARMa/commit/32cbadc369ba82ce864064ddd3df9ac571dbc933 and glmmTMB 1.0

**Comment by florianhartig** [comment]
Since DHARMa 0.2.7 and glmmTMB 1.0, it seems all problems are solved, and I will close this now!

**Comment by mebrooks** [comment]
Hurray!

**Comment by florianhartig** [comment]
What remains open is to ability to condition on REs when simulating, see https://github.com/glmmTMB/glmmTMB/issues/888
