### ISSUE TITLE
DHARMa for NB model 

### ISSUE THREAD

**Issue by WisamSaleem** [florianhartig/DHARMa#186]
Hi Florian.
I need to analyze the goodness of fit of NB model with overdispersion, i.e. MASS::glm.nb().
I am a bit skeptical about the results and plots I have got from DHARMa, which is a very helpful and powerful package.
Could you please, highlight any critical points I have to take into consideration when using DHARMa package for the NB model precisely.

Many thanks
Wisam

**Comment by florianhartig** [comment]
Hi Wisam,

you can diagnose the nb in the same way as all the poisson examples in the vignette. If you post your model and diagnostics here, as well as your doubts, I can give you more specific feedback!

Best,
Florian

**Comment by WisamSaleem** [comment]
Dear Florian.
The plots are informative and DHARMa makes my life easier.
Many thanks. 

Wisam

**Comment by florianhartig** [comment]
OK, glad to hear this! I will close this.
