### ISSUE TITLE
Memory Allocation “Error: cannot allocate vector of size 29.8 Gb"

### ISSUE THREAD

**Issue by thuvuong2019** [florianhartig/DHARMa#187]
Hi,
I am a novice user of R and new to DHARMa.

I have been running a multilevel model and have used DHARMa for model diagnostics, using the code below:

simulationOutput <- simulateResiduals(fittedModel = LOS_nb1_7, plot = T)

However, I came across this error “Error: cannot allocate vector of size 29.8 Gb”. I have been spending a lot of time doing research to find ways to fix this error. I tried to increase to memory limit to 29.8 Gb, I got the below message: 

Error in memory.limit(size = 29800) : 
  don't be silly!: your machine has a 4Gb address limit. 

Then I thought there might be limited memory with my laptop. I checked and I have 74.4 Gb free of 222 Gb. So I am not sure why it does not let me increase the memory limit.

I then went to the office at the University to use the PC, and it works fine.

I am not sure if this has something to do with compatibility issue between R version/Rstudio version with DHARMa version that causes this problem. 

I was wondering if I could receive some help.

Thanks very much for your time.
Thu Vuong

**Comment by florianhartig** [comment]
Hi Thu Vuong,

the message is about your RAM, not your HD - R has the limitation that all your data has to fit in RAM. 

It sounds to me as if you're fitting a very large dataset with millions of observations? What regression package are you using, and can you describe the properties of your data (dimensions)?

Of course, the easiest thing would be to reduce n (simulations), but if you have a standard laptop with 16GB or RAM or so, you would have set n to 100 or so, which is not ideal for precision of the DHARMa tests. Alternatively, you could run this on a computer with more RAM. 

Best,
Florian

**Comment by florianhartig** [comment]
p.s. - see also https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/memory.size and discussion about memory limits in R via google

**Comment by thuvuong2019** [comment]
Hi Florian,
Thanks for your reply.
Yes, I am fitting a large data set (neally 100,000 observations in a
multilevel model with 5 levels). The size of the model object after fitting
can be up to 22 MB.
I have tried to reduce the n (simulations) to 200 but it still did not work.
And Yes, you are right. I tried with the PC at work with more RAM and it
produced the output.
I guess the solution is to have to use the PC with more RAM. Do you think
it might work on my laptop if I have an external hard drive with a lot of
RAM?
Thank you very much for your time.
Thu

**Comment by florianhartig** [comment]
Hi Thu,

I'm not sure if something can be done on the DHARMa side, but I have opened an issue here #188 for future development. 

At the moment, I don't see an immediate fix to this, so it boils down to either using a computer with more memory (which seems possible for you, so I would recommend doing that), or possibly playing around with your memory allocation for your R environment (could be dangerous though if you set it beyond your physical memory. 

Best,
Florian

**Comment by thuvuong2019** [comment]
Hi Florian,
Thanks very much for the suggestion and confirmation.
Really appreciate your time with this.
Best regards,
Thu

**Comment by florianhartig** [comment]
no prob. closed!
