### ISSUE TITLE
testSpatialAutocorrelation() returns an ape: :Moran.I error

### ISSUE THREAD

**Issue by schis023** [florianhartig/DHARMa#190]
Hello,

I have a data set of multiple locations (approx. 14 000 unique coordinate points) that have been sampled multiple times over ~10 years. I'm building mixed models with these data and I want to test the residuals for spatial autocorrelation. Following this package's recommendations, I used `recalculateResiduals()` to account for the multiple samples for each location as follows:  

```
sims <- simulateResiduals(model1)
groupedSims <- recalculateResiduals(sims, group = df$Site) # Where Site indicates each location with a unique coordinate point.
``` 
This works fine up to the point where I use `testSpatialAutocorrelation()`. First I isolated one year's worth of coordinate points so that I have a data frame of unique coordinates to refer to. Then I plugged in these unique coordinates into `testSpatialAutocorrelation()`:

```
year1 <- df[(df$YEAR == 2000),]
coords <- data.frame(LONG = c(year1$LONG), LAT = c(year1$LAT))

testSpatialAutocorrelation(groupedSims,coords$LONG,coords$LAT,plot=FALSE)
```
This returns the error:
```
Error in ape::Moran.I(simulationOutput$scaledResiduals, weight = invDistMat,  : 
  'weight' must have as many rows as observations in 'x'
```
Any ideas about what might be going on and how to resolve this problem?

Thank you!

**Comment by florianhartig** [comment]
There is with near certainty some problem in your data structure. Check:

- groupedSims plots fine?
- how many residuals are in groupedSims?
- how many rows does coords have? Does this match?
- are there any duplicates in coords?

I should probably check these things and implement a more meaningful error message. 

Best,
Florian

**Comment by schis023** [comment]
Thanks for your suggestions Florian. 

After digging into the structure of my data set, I did indeed find the problem there. One of my sites had two separate locations in space, resulting in two unique coordinate points for one site with the same ID. This resulted in one extra value in 'coords' compared to the number of residuals in 'groupedSims'. After giving the two locations unique site IDs and re-running the code above, `testSpatialAutocorrelation()` worked just fine.

Cheers,
Sarah

**Comment by florianhartig** [comment]
Hi Sarah,

thanks for the feedback - I'll keep the issue open as a reminder to implement a more meaningful error message.

Best,
Florian

**Comment by florianhartig** [comment]
@EttnerAndreas - could you have a look at this?
