### ISSUE TITLE
overdispersion in NB

### ISSUE THREAD

**Issue by WisamSaleem** [florianhartig/DHARMa#203]
Hi Florian Hartig.
There is a situation for overdispersion in NB model where the variance of the model exceeds (mu + mu^2 * alpha).
Does the testDispersion() function investigate that issue with NB, but with simulated data instead of the fitted values.

Best Regards
Wisam

**Comment by florianhartig** [comment]
Hi Wisam,

I'm not 100% sure what you mean with exceeds (mu + mu^2 * alpha) - can you give an example? Would you like the dispersion test to react to this or is this case?

Technically, the dispersion test simulates data from the fitted model, and compares the variance (to be exact, the sd of residuals) of that simulated data with the same value for the observed data. 

In that sense, the test should be able to detect a deviation of said measure (sd or residuals) under any circumstances.

Cheers,
Florian

**Comment by florianhartig** [comment]
In doubt, maybe just simulate an example and post it here?

**Comment by WisamSaleem** [comment]
Thank you for your reply.
Actually, the idea of overdispersed NB is used by Joseph Hilbe in (Negative Binomial Regression).
Excuse my ignorance as I tried to understand and maybe I just confused things.
I shall try to implement the example here:

library(MASS)
library(DHARMa)
library(microbiome)
tax<- "Streptococcus bovis et rel."
m<- meta(atlas1006)[,-c(1,2,4,5,7,8,10)]  
m$signal<- get_sample(atlas1006, tax)
plonb<- glm.nb(signal ~ ., data = m)

## By calculating the model variance as:
var.mod<- plonb$fitted.values + ((plonb$fitted.values)^2 * summary.glm(plonb)$dispersion)

### Do you think my understanding is correct till now? If so, what is the variance of the data, and how can I compare it to the model variance. That the reason I asked about testDispersion(NB model).

Many thanks for your patience.
Wisam

**Comment by florianhartig** [comment]
Hi @WisamSaleem - I'm sorry, I think I forgot to reply to your comment, and it seems you erased it? Anyway, I think what you wrote is just that the NB has a parameter for the dispersion, thus the variance may exceed the standard Poisson variance. 

In any case, DHARMa tests take care of all that, so there is no problem applying the testDispersion to a NB model (apart from the fact that you likely won't find overdispersion, as the NB can adjust dispersion)

**Comment by WisamSaleem** [comment]
​Dear Florian,
Thanks a lot, no problem. I used your DHARMa package actively.

Wisam
