### ISSUE TITLE
recalculateResiduals when sample size varies between groups

### ISSUE THREAD

**Issue by owmug** [florianhartig/DHARMa#218]
Hi Florian,

I am using function recalculateResiduals to obtain residuals for each of my sample sites. The sample size varies between sites and I wonder if this is an issue when recalculating residuals? For background, I want to test for residual spatial autocorrelation for a model with sites as a random effect.

Thanks,

Ute

**Comment by florianhartig** [comment]
Hi Ute,

I don't think it's an issue per se, in the sense that we are always testing against a H0 which is that residuals show no pattern, i.e. they should also no pattern if you aggregate them in some random, unbalanced fashion.

In some particular cases, however, it could create some weird effects. I am thinking, e.g., if you plot residuals in space, to test for spatial autocorrelation. The residuals that have less data behind them will tend to be noisier, and thus spatial autocorrelation (if it exists) would likely be less pronounced for them. Likewise, if there is overdispersion in a k/n binomial, this would probably show up more strongly in the residuals that have more data behind them. In these cases, you could have pattern that come out more strongly for the residuals with more data behind them. 

For the latter reasons, it could be that certain problems would be easier to detect with a balanced aggregation (e.g. by grouping data points), but on the other hand, an unbalanced grouping should not create any pattern in the residuals, so I don't see a  reason why you shouldn't look  at the unbalanced residuals.

**Comment by owmug** [comment]
Hi Florian,

thanks for your reply.

I also wonder about the aggregateBy argument in the recalculateResiduals function. I am afraid I don't fully understand how the residuals are recalculated, so I wonder if for unbalanced group sizes this argument should be changed from sum to mean?

Thanks,

Ute

**Comment by florianhartig** [comment]
No, this is an independent decision. Whatever function you use, the residuals are always calculated by comparing the observed values to simulations, both wrt the the function you choose to aggregate the values per group. Sum and mean would actually give the same result (as mean is only a rescaling of sum), but mean and median would be different, for example, but I wouldn't make changes, just keep the default, this has nothing to do with your problem.

**Comment by owmug** [comment]
Thanks for the explanation.
