### ISSUE TITLE
How to change colors in plot() or plotResiduals() 

### ISSUE THREAD

**Issue by SchmidtPaul** [florianhartig/DHARMa#219]
Hi there,
great work so far! Sorry if I am missing something here, but is it possible to finetune the residual plot from `plotResiduals()` or even both plots from `simulateResiduals() %>% plot()`? Mostly, I would like to color individual residuals according to their respective factor levels in order to investigate patterns. In ggplot2 syntax this would be `aes(color = factor)` and in DHARMa it could be something like this, I guess:

``` r
library(tidyverse)
library(lme4)
library(DHARMa)

mod <- iris %>% 
  mutate(Petal.Length_factor = ifelse(Petal.Length < 4.2, "A", "B")) %>% 
  lme4::lmer(Sepal.Width ~ Species + Petal.Width + (1 | Petal.Length_factor), data = .)

mod %>% 
  DHARMa::plotResiduals(col = Species)

mod %>% 
  DHARMa::simulateResiduals() %>% plot(col = Species)
```

**Comment by florianhartig** [comment]
Hi Paul, 

standard graphic parameters can be forwarded in plotResiduals() via ..., see help file of plotResiduals() and plot(). 

Your problem is that species is not in the global environment, this works: 

```
mod %>% 
  DHARMa::plotResiduals(col = iris$Species)
```

**Comment by SchmidtPaul** [comment]
Hi Florian,
whoops sorry for not noticing that myself and thanks for the quick reply!
For completeness and in case anyone else stumbles across this, here is the working example:

``` r
library(tidyverse)
library(lme4)
library(DHARMa)

dat <- iris %>% 
  mutate(Petal.Length_factor = ifelse(Petal.Length < 4.2, "A", "B"))

mod <- lme4::lmer(Sepal.Width ~ Species + Petal.Width + (1 | Petal.Length_factor), 
                  data = dat)

mod %>% 
  DHARMa::simulateResiduals() %>% 
  plot(col = dat$Species)
```
![image](https://user-images.githubusercontent.com/31928213/102463036-db8adb00-404a-11eb-8129-0fec9e77c8f7.png)
