### ISSUE TITLE
Migrate CI from travis to GH actions

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#232]
See https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by florianhartig** [comment]
See examples in https://github.com/TheoreticalEcology/s-jSDM/actions

**Comment by MaximilianPi** [comment]
Could be a good starting point https://usethis.r-lib.org/reference/use_github_action.html  :
`usethis::use_github_action("check-standard")`

**Comment by florianhartig** [comment]
Thanks Max. @EttnerAndreas, can you try this out in your fork? (no rush)

**Comment by EttnerAndreas** [comment]
Warning: sfsmisc::factorize’ is replaced by ‘lme4::factorize

**Comment by florianhartig** [comment]
I don't understand the proposed solution - I have looked, we are neither explicitly importing sfsmisc nor lme4, and I sfsmisc is only used for sfsmisc::posdefify  in some place. 

So, actually, I don't really understand why the error occurs. 

About the solution: do you mean we should strike sfsmisc from depends, and include the function as a native DHARMa function? Can you post a link where this is suggested?

**Comment by florianhartig** [comment]
One more question: I see you deleted the travis.yml - is this necessary, or ist it possible to test with Travis and GH Actions in parallel?

**Comment by EttnerAndreas** [comment]
>  I have looked, we are neither explicitly importing sfsmisc nor lme4
In the Description of DHARMa both, sfsmisc and lme4 are listed for import, it might be due to this that GitHub Action is installing it.

**Comment by florianhartig** [comment]
yes, but installing it shouldn't create the warning, the warning is only created when both packages are loaded. OK, but apparently this happens when the package is installed ... odd

**Comment by florianhartig** [comment]
hmm ... apparently, this is not true https://stackoverflow.com/questions/19838360/how-to-import-only-one-function-from-another-package-without-loading-the-entire

**Comment by florianhartig** [comment]
OK, then there are two options: 

1) find out how we can suppress the warning

2) find out if we can include sfsmisc::posdefify

About 2: from a quick glance, it looks as if this is only using base functions, so in principle this could work. Can you check out if the function works for you if you just paste it in your console (with a new R version, no packages loaded?) 

```
> sfsmisc::posdefify
function (m, method = c("someEVadd", "allEVadd"), symmetric = TRUE, 
    eigen.m = eigen(m, symmetric = symmetric), eps.ev = 1e-07) 
{
    stopifnot(is.numeric(m) && is.matrix(m))
    method <- match.arg(method)
    n <- length(lam <- eigen.m$values)
    Eps <- eps.ev * abs(lam[1])
    if (lam[n] < Eps) {
        switch(method, someEVadd = lam[lam < Eps] <- Eps, allEVadd = lam <- lam + 
            Eps - lam[n])
        Q <- eigen.m$vectors
        o.diag <- diag(m)
        m <- Q %*% (lam * t(Q))
        D <- sqrt(pmax(Eps, o.diag)/diag(m))
        m[] <- D * m * rep(D, each = n)
    }
    m
}
```

**Comment by EttnerAndreas** [comment]
> One more question: I see you deleted the travis.yml - is this necessary, or is it possible to test with Travis and GH Actions in parallel?

No problem running both. While TravisCI is passing any checks, Github Action is still failing the checks  #[see URL](https://github.com/EttnerAndreas/DHARMa/tree/TRAVIS_ACTION)

**Comment by florianhartig** [comment]
OK, then I actually think it's better if you could try to add this to your GH Action branch before I change this in DHARMa. Try this:

- Remove sfsmisc from description 
- remve sfsmisc:: from sfsmisc::posdefify in the code
- add the function with name posdefify somewhere in the R code

**Comment by EttnerAndreas** [comment]
removing sfsmisc from description 'Imports' to 'Suggests' lead to:

**Comment by EttnerAndreas** [comment]
running the 'standard' Version is leeding to an overall success but less checks
![Screenshot (209)](https://user-images.githubusercontent.com/70816016/106901721-648fcb80-66f8-11eb-9d3d-6a73ea7a0db4.png)

**Comment by florianhartig** [comment]
OK, it seems lme4 can't be installed on ubuntu 16 with old R versions - I don't think it's important to check these old ubuntu versions with old R versions, so we can ignore this. 

The standard configuration seems fine to me, except that it would be interesting to have an oldrelease version in there. Is there a configuration that has an old release included, which should be current R 3.6.x according to https://win-builder.r-project.org/ ?

**Comment by florianhartig** [comment]
About the suggest switch: if that solves the problem, it's probably fine as well. sfsmisc::posdefify is used only in createData, which is not really a core function for most users, but rather used in the tests.

**Comment by florianhartig** [comment]
OK, I moved packages that are not in the core functions now all to suggests with https://github.com/florianhartig/DHARMa/commit/485957dad781c2992fedccfe3e3da5041d06540d

**Comment by florianhartig** [comment]
Hi @EttnerAndreas, better write here than on slack, so that we have a record of the conversation. OK, last think I heard everything works fine? In this case, I would simply copy the .github directory from your brach to this here (I would avoid a pull request) and that should do the trick?

Also, I just to note saw that https://github.com/glmmTMB/glmmTMB/issues/655 are also working on the migration, maybe useful to follow the discussion there as well.

**Comment by EttnerAndreas** [comment]
https://github.com/EttnerAndreas/DHARMa/tree/TRAVIS_ACTION

At the moment I am trying to discover whether different R versions are tested and if so, which one, but so far no clear answer to me.
I will keep an eye on the glmmTMB conversation

**Comment by florianhartig** [comment]
We know that, right? In your 'standard' Version we have release and devel. This is finde, only thing that would be desirable would be to have oldrel in the test. As currently in https://travis-ci.com/github/florianhartig/DHARMa/builds/216076746

What we don't want is a test with a fixed version number.

**Comment by florianhartig** [comment]
see if possible to do similar as in  https://github.com/florianhartig/DHARMa/blob/0e0d2370ec8250ca2cac007ba12cd7b993acefc6/.travis.yml#L2

See also https://github.com/TheoreticalEcology/s-jSDM

**Comment by florianhartig** [comment]
Hi @EttnerAndreas uff, I'm just fighting wit smaller bugs, which also made me realize that the GH actions never realize that there is a bug when there is indeed one (while TRAVIS does). See e.g. current PRs.

Are you sure they are running R checks?

**Comment by EttnerAndreas** [comment]
Hi @florianhartig I checked it and it seems like we are checking only the package itself, but I am currently working on integrating the tests
