### ISSUE TITLE
Interpretation of the test statistic of testDispersion

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#234]
Question from a user

> When I calculate the dispersion parameter (deviance/df.residuals) I get a very different number from the output of testDispersion. I assume it has to do with the simulated residuals? 
> 
> Is the "ratio" in the output of the function the dispersion parameter?
> If so, why is it so different from the calculated dispersion parameter, and which do I believe?

**Comment by florianhartig** [comment]
No, this has nothing to do with simulated residuals.

For testing if something deviates from expectation, you need a test statistics. The current default test statistic in the DHARMa dispersion test (as of DHARMa 0.3.3) is the observed / simulated standard deviation of the data. In the following example, we have a ratio of 1.16, so the sd of the observed data is 1.16 higher as the sd of the data simulated under the fitted model. And given the null distribution, this is significant. 

![image](https://user-images.githubusercontent.com/5457753/106139331-94c1f200-616d-11eb-9809-60b4a140078c.png)

The residual deviance by the degrees of freedom can be viewed as another possible test statistic / indicator. It is motivated by the idea that, asymptotically, the deviance of a GLM should be chi-square distributed with mean equal to the degrees of freedom, so deviance / df ~ 1. Note, however, that this is an approximation that may not hold for all models / data, in particular not for GLMMs for which the df is somewhat unclear. Moreover, deviance (= essentially fit) is also influenced by factors, so this is not really testing for overdispersion, but more for a general GOF. 

So, there is nothing surprising about the fact that the two values differ. The two are two completely different statistics, albeit often used for a similar purpose. Moreover, I would note that I wouldn't call deviance / df a dispersion parameter. For me, the a dispersion parameter is a parameter of a model, such as theta in the neg. binom. Deviance / df is simply a GOF metric.

**Comment by florianhartig** [comment]
Note: in 3990eda557fa109a6375fd301c7ddf2b52397342, test statistics was changed to standardized var to better conform with traditional tests for dispersion.

**Comment by KuepferA** [comment]
Does a significant p-value for testDispersion(model) signify over-dispersion? I assume this is the case, but have not found any documentation on this.

**Comment by florianhartig** [comment]
Per default, the test is two-sided, so you have to look at the dispersion parameter to see if a significant p-value means under or overdispersion. See help for details.
