### ISSUE TITLE
output of testQuantiles for gamma model is NULL

### ISSUE THREAD

**Issue by biellia** [florianhartig/DHARMa#240]
I am fitting this model
`m1.dczig <- glmmTMB(Res.dia.pers ~ Tipo + (1|ID) , data=all, zi=~ Tipo , family=ziGamma(link ="log")) `

where Res.dia.pers is a continuous variable >= zero, and Tipo is a categorical variable.

I am using DHARMa for model diagnostics and I have two questions:
1- the output of testQuantiles is NULL (but the graph does show up): what does NULL mean? Is there a specific reason?
```
> testQuantiles(simulationOutput) 
NULL
```
2- from plot(simulationOutput) shows significant dispersion. I thought over/underdispersion was not relevant for gamma models, is this referred to the ziformula?

```
> testDispersion(simulationOutput) 
DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

data:  simulationOutput
ratioObsSim = 0.58, p-value <2e-16
alternative hypothesis: two.sided
````
I appreciate your help, please let me know if more details can be useful to this issue. Thanks!

**Comment by florianhartig** [comment]
Hi biellia, 

1) is indeed a bug, which I just realised. If you set plot = T, the test falls back on the quantile plot, and if nObs < 2000, this plot suppresses the quantile calculations. I should fix this. Anyway, if you set plot = F, the quantile tests will be calculated. Could be slow if you have a large dataset. Alternatively, you can set quantreg = T in plotResiduals. 

2) It's true that the gamma model has a dispersion parameter, but that doesn't mean that fitting the model will set this parameter on a value that makes the dispersion test n.s. . The dispersion test compares simulated vs. observed variance in the data. What it tells you is that the observed data seems to have less dispersion than the simulated data.  This could have any number of reasons, e.g. that the Gamma doesn't fit well to your data. 

Maybe I can say more if you could paste a few residual plots here, at least the main DHARMa residual plot?

**Comment by florianhartig** [comment]
1) is now fixed in the development version of DHARMa (install via https://github.com/florianhartig/DHARMa)

**Comment by biellia** [comment]
Dear Florian

1. thanks so much for fixing the bug
2. Here a couple of plots. In my dataset, the values of the dependent variable for one level of my categorical predictor are higher and more dispersed compared to the other levels. Maybe it is the cause of the significant dispersion test. Also, the quantile test is significant.

Thanks for your help,

Alessandra

![image](https://user-images.githubusercontent.com/68022416/106959479-55ad1700-6700-11eb-8c40-61d27678474a.png)

**Comment by florianhartig** [comment]
Hi Alessandra,

if you see the different dispersions across groups (I suspect the groups are Tipo), why not just add dispformula = ~ Tipo to your model? 

Best,
F

**Comment by biellia** [comment]
Hi Florian,

That fixed all the problems and the plots look great, thanks!

I have not used dispformula before, how does it work? is it possible to use it for predictions?
I have found the info [here](https://journal.r-project.org/archive/2017/RJ-2017-066/RJ-2017-066.pdf), equations 1 to 5, but I am not sure how to use this info for my case.

I am currently using this code to predict at the population mode:
```
newdata0 = with(all,
                        expand.grid(
                            Tipo = c("1","2","3","4")))
X.cond = model.matrix(lme4::nobars(formula(m1.dczig)[-2]), newdata0)
beta.cond = fixef(m1.dczig)$cond
pred.cond = X.cond %*% beta.cond
ziformula = m1.dczig$modelInfo$allForm$ziformula
X.zi = model.matrix(lme4::nobars(ziformula), newdata0)
beta.zi = fixef(m1.dczig)$zi
pred.zi = X.zi %*% beta.zi

pred.ucount = exp(pred.cond)*(1-plogis(pred.zi))

set.seed(101)
pred.condpar.psim = mvrnorm(1000,mu=beta.cond,Sigma=vcov(m1.dczig)$cond)
pred.cond.psim = X.cond %*% t(pred.condpar.psim)
pred.zipar.psim = mvrnorm(1000,mu=beta.zi,Sigma=vcov(m1.dczig)$zi)
pred.zi.psim = X.zi %*% t(pred.zipar.psim)
pred.ucount.psim = exp(pred.cond.psim)*(1-plogis(pred.zi.psim))
ci.ucount = t(apply(pred.ucount.psim,1,quantile,c(0.025,0.975)))
ci.ucount = data.frame(ci.ucount)
names(ci.ucount) = c("ucount.low","ucount.high")
pred.ucount = data.frame(newdata0, pred.ucount, ci.ucount)
```
I adapt it by adding 

```
dispformula = m1.dczig$modelInfo$allForm$dispformula
X.disp = model.matrix(lme4::nobars(dispformula), newdata0)
beta.disp = fixef(m1.dczig)$disp
pred.disp = X.disp %*% beta.disp

pred.disppar.psim = mvrnorm(1000,mu=beta.disp,Sigma=vcov(m1.dczig)$disp)
pred.disp.psim = X.disp %*% t(pred.disppar.psim)
```
How do I include the dispersion parameter in the `pred.ucount = exp(pred.cond)*(1-plogis(pred.zi)) ` and `pred.ucount.psim = exp(pred.cond.psim)*(1-plogis(pred.zi.psim))`?

Thanks again!

**Comment by florianhartig** [comment]
The ~ dispformula will fit the specified regression for the dispersion parameter of the respective distribution, which is in this case the Gamma, in the same way as the zi term. See glmmTMB help for details. 

I suspect that this does not affect the mean prediction, but why do you not use https://www.rdocumentation.org/packages/glmmTMB/versions/1.0.2.1/topics/predict.glmmTMB for predictions?

In general, these are all glmmTMB specific questions, on which I am not an expert. I would suggest asking this to the guys over at https://github.com/glmmTMB/glmmTMB/issues

**Comment by florianhartig** [comment]
I would say problem solved, so I will close!
