### ISSUE TITLE
How to handle line ending phantom changes Mac / Windows

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#250]
Find out how we avoid git diffs / commits detecting changes in line endings when editing on Windows / Mac, as in, e.g., https://github.com/florianhartig/DHARMa/pull/249/commits/005d3003a537fcdaf8341747946622e9cad83018

**Comment by EttnerAndreas** [comment]
See @https://github.com/rstudio/rstudio/issues/1929
on windows & Linus the new line is the \n escape sequence, while Mac is using \r
Solution: change local settings in Tools -> Global Options -> Code -> Saving
I recently changed from

**Comment by florianhartig** [comment]
Hi Andreas, just to clarify: you changed on your system, so we're good now? In this case you can close the issue!

**Comment by EttnerAndreas** [comment]
yes, there should not occur further problems with the line endings
