### ISSUE TITLE
Unable to set seed=NULL in simulate residuals

### ISSUE THREAD

**Issue by jmniehaus** [florianhartig/DHARMa#254]
Hello, 

I am attempting to write my own `simulate` function for a package I am implementing that will rely on dharma. I am trying to use dharma's `getRandomState` function at the beginning of my `simulate` function, similarly to dharma's `simulateResiduals` function. However, when I use `seed=NULL`, I get an error due to a logical problem in `getRandomState`, I think. 

Reprex: 
```
y = rnorm(100)
x = rnorm(100)
mod = lm(y~x) 
simulateResiduals(mod, seed=NULL)

> Error in if (is.logical(seed) & seed == F) { : argument is of length zero
```

Because `seed=NULL`, `NULL==F` returns a zero-length vector.

**Comment by florianhartig** [comment]
OK, but why is that a problem? What would be your desired behaviour for seed = NULL?

**Comment by florianhartig** [comment]
OK, sorry, I see that the help specifies that this should work. I will have to dig into that!

**Comment by florianhartig** [comment]
This was indeed a bug, thanks for reporting this. I am just running the tests and will push this to master in a second (for how to install, see start page). 

About your simulate function - is this a regression package, or a package that requires simulations? If the former, note https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA, if the latter, note that DHARMa as internal S3 wrappers for the supported package in file compatibility.R, see ?DHARMa::getSimulations
