### ISSUE TITLE
0.3.4 final polishing

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#260]
- Test if everything works, run help files etc., in particular regarding the newly implemented functions
- Check help files
- Check main vignette (are the new options explained)

**Comment by florianhartig** [comment]
TODO - check if NEWS file is complete

**Comment by florianhartig** [comment]
Hi Andreas, I really want to get 0.3.4 ready for submission this WE, if you have any time, could you:

* Check commits between 0.3.3 and now for important changes that are not in NEWS (unfortunately, I haven't been super tidy about this)
* Build the package and check with https://win-builder.r-project.org/ for any problems. Warnings and notes also might be problems. Post problems here, in case you can't immediately fix them 
* Build the package and run examples / help etc. to see if anything looks fishy to you, in particular new functions!

**Comment by EttnerAndreas** [comment]
NEWS file:
Line 24: **bugfix in runBenchmarks** -  missing URL Link, if provided, might be interesting

How about the minor change (new **selection** parameter) on **RecalcuateResiduals**?

**Comment by EttnerAndreas** [comment]
NEWS file:
Did we finally fix the SpatialAutocorrelation statements? see Issue #190 (also see https://github.com/florianhartig/DHARMa/commit/4da5af3fbf1f94f9ef59a8ca604decd49b636126)

furthermore implemented **'selection'** in recalculateResiduals #246

**Comment by florianhartig** [comment]
OK, I have made the changes in the NEWS file. #190 does not need to be mentioned I guess. For spelling mistakes etc - could you just change make a PR for all spelling issues etc. that you find?

**Comment by EttnerAndreas** [comment]
yes sure, think a PR for that makes sense. I´ll send the PR later that night

**Comment by EttnerAndreas** [comment]
I recently took a closer look at the new **"returnStatistics"** function (also see https://github.com/florianhartig/DHARMa/commit/9fe5290d7c0bf153c538127cb05969423851b4c5)
- A help file could be useful, since the function measures the Disperson quite differently. 


furthermore, I realized that runBenchmarks, with the advanced settings **"controlValues"**  has a big difference in the plot(output), but the help file is not that clear to me, how to use **"controlValues"**. 
- I would suggest further explanation

**Comment by florianhartig** [comment]
Hi Andreas, but returnStatistics is not a function of DHARMa, it's just a function in the help, right?

I have added a few more explanations in the help of both functions, have a look if it is clearer now. I think having a perfect help in this function is less critical, as this is not typically used by the normal users, it's more an internal benchmarking function.

**Comment by EttnerAndreas** [comment]
Hi Florian, yes returnStatistics is not a DHARMa function, but since it is new and I had to think about the function twice, I thought it makes sense to recommend it here.

I think the new explanations are very helpfull. Thanks
For your information, the other helpfiles were clear to me. But there was not much code added since the last release.

**Comment by florianhartig** [comment]
OK, I thought we are basically done, I had run the winbuilder tests before, without problems, I just did a final run and this time we get errors from qgam, no idea if this is just a stochastic problem? Will trigger another build to check this 

![image](https://user-images.githubusercontent.com/5457753/111120759-0f06d400-856c-11eb-92d7-2e1fc647963a.png)

**Comment by florianhartig** [comment]
OK, re-triggering the build resolved the problem ... not sure, if this was a stochastic problem, we could probably set.seed() to solve this, but actually the code should work with any seed, so I will leave this for now.

**Comment by florianhartig** [comment]
OK, seems to me 0.3.4 would be ready for CRAN ... ??

Andreas, have you made checks with glmmAdaptive?

**Comment by EttnerAndreas** [comment]
hopefully glmmAdaptive will be finished by tomorrow morning,
I need some more time for the unit tests

**Comment by florianhartig** [comment]
Hi Andreas, sorry, I just looked at the unit tests, it seems you tested glmmAdaptive itself? What I mean is to test if it works with DHARMa?
