### ISSUE TITLE
fittedPredictedResponse = fittedResiduals

### ISSUE THREAD

**Issue by awcm0n** [florianhartig/DHARMa#270]
I simulated data from a linear probability model that was fit with `stats::lm()`. 
`sim <- simulateResiduals(fittedModel = m1, plot = F)`

In the resulting object, fittedPredictedResponse equals fittedResiduals.

> head(sim$fittedPredictedResponse)
        1         3         4         5         6         7 
0.4089331 0.4666357 0.3593490 0.4289471 0.5312127 0.3483226

> head(sim$fittedResiduals)
        1         3         4         5         6         7 
0.4089331 0.4666357 0.3593490 0.4289471 0.5312127 0.3483226

**Comment by florianhartig** [comment]
This should only happen if you model fits the data perfectly, i.e. if R2 is nearly 1, meaning that you residual sd is close to zero, in which case there would be nothing to simulate. Could you provide a reproducible example?

**Comment by florianhartig** [comment]
Ah, sorry, I just made a mistake, this is not about the simulations, hang on, let me check first.

**Comment by florianhartig** [comment]
Thanks for bringing this to my attention, the devil is in the details. There was indeed a small bug in the S3 dispatchment of the getResiduals function, as you can see in the change above. 

Unfortunately, this has some downstream consequences, as those residuals were used in the quantile residuals when simulating with refit = T. For most users, this should be of no consequence, but I will probably still push an immediate update to CRAN to fix this (should be 0.3.5).
