### ISSUE TITLE
Bug with PIT residuals in refit = T

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#272]
Thanks to a question, I just realized that there is a bug in refit = T for quite a while. This becomes visible when running 

```
testData <- createData(500, family = binomial())
fit <- glm(observedResponse ~ Environment1, family = binomial, data = testData)
simulateResiduals(fittedModel=fit,n=100,refit=T,plot=T)
```
This worked fine in DHARMa 0.3.0

![image](https://user-images.githubusercontent.com/5457753/113989303-99331700-9850-11eb-9ae7-76506b03322b.png)

and breaks in DHARMa 0.3.1 when I introduced the PIT residuals

![image](https://user-images.githubusercontent.com/5457753/113989443-bc5dc680-9850-11eb-9806-af195a7e1716.png)

One can see that it is specifically the PIT residuals, because

`res <- simulateResiduals(fittedModel=fit,n=100,refit=T,plot=F, method = "traditional")`

works as before. 

Also, unrelated, I just realized the outlier tests are extremely slow for refit = T, something to look at as well. It's a bit embarrassing that I didn't notice this before, in my defense, I rarely use refit = T. Anyway, I'll have to fix this asap.

To test this, switch DHARMa versions via.

```
devtools::install_github(repo = "florianhartig/DHARMa", subdir = "DHARMa", 
                         ref = "v0.3.1.0", dependencies = F, build_vignettes = F, force = T)
```

**Comment by florianhartig** [comment]
@EttnerAndreas - can you have a look at this to confirm? I find it very odd that I didn't notice this before, but it seems it was there since 0.3.1

**Comment by florianhartig** [comment]
Just an add-on: it is specifically the PIT residuals, because 

`res <- simulateResiduals(fittedModel=fit,n=100,refit=T,plot=F, method = "traditional")`

works as before. Also, unrelated, I just realized the outlier tests are extremely slow for refit = T, something to look at as well.

**Comment by EttnerAndreas** [comment]
@florianhartig Sure, I will test that.

**Comment by florianhartig** [comment]
OK, this was easier than I though, after a bit of reflection I realized that the entire PIT procedure simply doesn't work with the way the refit residuals are currently simulated. So, I switched back to the traditional method for now.

**Comment by florianhartig** [comment]
For future reference: the issue is that the refit = T compares the distribution of simulated residuals to observed, but those will become continuous even for 0/1 data, so the PIT doesn't smoothen out the distribution, in the way the "traditional" method does.
