### ISSUE TITLE
Title of plotResiduals() is incorrect if form is provided

### ISSUE THREAD

**Issue by LisaHuelsmann** [florianhartig/DHARMa#274]
If the argument form is provided, the caption for `plotResiduals()` is **Residuals vs. predicted** although it should probably be something like **Residuals vs. predictor**. 
See `plotResiduals(simulationOutput, form = testData$Environment1, quantreg = FALSE)` for example.

**Comment by florianhartig** [comment]
Thanks, will fix this now!
