### ISSUE TITLE
Weird residuals plot

### ISSUE THREAD

**Issue by ddris** [florianhartig/DHARMa#283]
I've fit a complex model to an enormous dataset and got a wierd residuals plot.

Model (some variables #ed out in model simplification process): 
m6 <-glmmTMB(Numbers ~ scale(Area) + scale(NPD)+ Habitat +
scale(Wing.Span) + HPUse + Mobility +Palatability+Transect.walks+
scale(Area):scale(Wing.Span)+
scale(Area):Mobility+
scale(Area):HPUse+
#scale(Area):Palatability +
scale(NPD):scale(Wing.Span)+
scale(NPD):Mobility+
scale(NPD):HPUse+
scale(NPD):Palatability +
Habitat:scale(Wing.Span)+
Habitat:Mobility+
Habitat:HPUse+
#Habitat:Palatability +

Habitat:scale(NPD)+
scale(Area):scale(NPD)+
scale(Area):Habitat+

scale(Area):scale(NPD): scale(Wing.Span)+
#scale(Area):scale(NPD):Mobility+
scale(Area):scale(NPD): HPUse +
#scale(Area):scale(NPD):Palatability+
 
#scale(NPD):Habitat: HPUse+
#scale(NPD):Habitat:scale(Wing.Span) +
scale(NPD):Habitat:Mobility+
#scale(NPD):Habitat: Palatability+
 
scale(Area):Habitat:Mobility+
scale(Area):Habitat:scale(Wing.Span) +
#scale(Area):Habitat:HPUse+
#scale(Area):Habitat:Palatability+

(1|Patch/Transect)+(1|Species), data=final3, family=binomial)

The dataset has 21000 rows, representing occurrence of 91 butterfly species across 236 transects in 48 patches.

> library(DHARMa)
> m6t<- simulateResiduals(fittedModel = m6, plot = F)
> plot(m6t)

![dharma qq and resid plot](https://user-images.githubusercontent.com/84839440/119629818-b8faba80-be51-11eb-9725-535530f3c086.jpg)
pg)

The plot doesn't look like any of the examples in the package information; it just has clusters of grit around the plot margins rather than circles intriguingly distributed across the plot area. Do you know what is going on?

**Comment by florianhartig** [comment]
Plots are changed to density plots and quantile residuals are surpressed for large data. You can overwrite this, see help. 

There is nothing special about these plots, but as noted in the vignette under binomial, residual problems in 0/1 binomial GLMs often show up only after aggregating data. See vignette for details.

**Comment by ddris** [comment]
Ah, it all makes sense now. Thanks.

Don
