### ISSUE TITLE
Error: need at least two non-NA values to interpolate

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [florianhartig/DHARMa#286]
Florian,

Thanks again for providing this wonderful package, and for addressing my previous comment regarding PIT residuals (#168)!

I coded VAST to use DHARMa by default, and in some cases have found an error resulting in the message

```R
Error in approxfun(vals, cumsum(tabulate(match(x, vals)))/(n + 1), method = "linear",  : 
  need at least two non-NA values to interpolate
```

after exploration, it appears to occur when calling all `DHARMa::createDHARMa` when argument `simulatedResponse` includes at least one row with all elements equal to 0.  This of course could happen by change alone, and is not a property of PIT residuals per se, but I'm guessing occurs when smoothing the `simulatedResponse` values prior to calculating a quantile value for that row.  As example, you could load this [RData object](https://drive.google.com/file/d/1eLi-hl4GjkbAuO1YvF8PloGj-TV3Kz_B/view?usp=sharing) to replicate the problem:

```R
dharmaRes = DHARMa::createDHARMa(simulatedResponse=all$simulatedResponse,
          observedResponse=all$observedResponse,
          fittedPredictedResponse=all$fittedPredictedResponse,
          method="PIT")
```

where e.g. the problem goes away when jittering any single value in each row:

```R
dharmaRes = DHARMa::createDHARMa(simulatedResponse=all$simulatedResponse + rep(1,nrow(all$simulatedResponse))%o%c(0.001*rnorm(1),rep(0,ncol(all$simulatedResponse)-1)),
          observedResponse=all$observedResponse,
          fittedPredictedResponse=all$fittedPredictedResponse,
          method="PIT")
```

As I say, the problem is not intrinsic to PIT residuals, because the unsmoothed values can be used to calculate a quantile.  Perhaps its worth giving users the option of turning off interpolation, or perhaps making that the default, to avoid this behavior?  I'd be happy to brainstorm ideas on this thread if that's helpful.

**Comment by Istalan** [comment]
Hello James,

I'm not Florian, but i am pretty sure that this is issue #195, which has been solved in current versions of the package. I've checked your example with 4.1 and it works just fine.

P.S. I've done quite a bit of work on this project and i think PIT was a fantastic addition to it.

**Comment by James-Thorson-NOAA** [comment]
Sorry to have addressed the issue to Florian;  I appreciate your help too, and everyone in involved with the project!

I'll close here and add some questions on #195

**Comment by florianhartig** [comment]
Hi @James-Thorson-NOAA - we can keep this closed, but just a clarification - can you confirm that the problem is solved with a newer version of DHARMa?

**Comment by James-Thorson-NOAA** [comment]
Yes, I have just downloaded R 4.1.0 and DHARMa 0.4.1 and confirmed that the problem is not present.  Thanks again.
