### ISSUE TITLE
Interpreting residual plots for checking heteroscedasticity by DHARMA package

### ISSUE THREAD

**Issue by Tahsin1990** [florianhartig/DHARMa#287]
Hi,

I am struggling to interpret the residual plots from the Dharma package. If we find a red line in residual plot,does it mean there is heteroscedasticity in the model for the predictor variables? If the solid line matches with the dashed line, can we say there is no heteroscedasticity? I have attached some residual plots here to understand heteroscedasticity of the model.  In the first plot, quantile deviation are detected by the red line, so there is heteroscedasticity in the model. This is for the model which includes all covariates. Then I created the residual plot for one by one covariate to know which predictors are responsible for variable dispersion. The 2nd and 3rd plots are for just one predictor. In the 2nd plot, three solid lines are red and there exhibits a clear deviation from the dashed line. So, there is heteroscedasticity in the model for that predictor. The 3rd plot is box plot.The distribution for each factor level should be uniformly distributed, so the box should go from 0.25 to 0.75, with the median line at 0.5 (within-group ). As the two box plots are red and it shows deviation of median line from 0.5, so there is heteroscedasticity in the model for the predictor. The 4th plot shows less deviation. Can we say this is better? I need your expert suggestions and also please refer me to any article where I find a clear explanation of heteroscedasticity checking by residual plot using DHARMA.Many thanks.

![Rplot1](https://user-images.githubusercontent.com/83094821/120565908-4fd3f380-c3cb-11eb-8b25-97002763f578.png)
![Rplot 2](https://user-images.githubusercontent.com/83094821/120565915-5498a780-c3cb-11eb-8240-7fe4934188c7.png)
![Rplot 3](https://user-images.githubusercontent.com/83094821/120565925-58c4c500-c3cb-11eb-80bc-929a26d66f31.png)
![Rplot 4](https://user-images.githubusercontent.com/83094821/120565933-5d897900-c3cb-11eb-919c-83977cb5530c.png)

Kindest regards,

Tahsin

**Comment by Istalan** [comment]
Hi Tahsin,

You're interpretation of the plots is, in my opinion, largely correct except that 3 and 4 don't show heteroscedasticity. They show a deviation from the expected , but they don't differ significantly over the predictor. If that deviation is big, as in 3, i would expect the Kolmogorov-Smirnov(KS)-test to  also be significant. 4 is looks fine, with only a few too many small values. The combined test being non significant being a strong argument, especially when combined with the KS-test.

Regarding your approach of refitting a mode with only one covariate: a more common and i also think more sensible approach would be to plot the residuals of the full model against each individual covariate. In Dharma this can be done by providing a `predictor` to `testQuantiles` Here a simulated Exmaple:

```
library(DHARMa)
#set.seed("0810")
testData = createData(sampleSize = 1000, fixedEffects = c(1, 1), quadraticFixedEffects = c(0, 1), family = poisson(), randomEffectVariance = 0)
fittedModel <- glm(observedResponse ~ Environment1 + Environment2, family = "poisson", data = testData)

res <- simulateResiduals(fittedModel = fittedModel)
plot(res)
summary(fittedModel)
testQuantiles(res)
# enviroment1 is fine
testQuantiles(res, predictor = testData$Environment1)
# enviroment2 wants to be quddtartic
testQuantiles(res, predictor = testData$Environment2)
fittedModel2 <- glm(observedResponse ~ Environment1 + Environment2 + I(Environment2^2), family = "poisson", data = testData)
res2 <- simulateResiduals(fittedModel = fittedModel2)
plot(res2)
```
 
Real examples with non independent covariates and other deviations from assumptions like over dispersion will be more complex, but the p-values of testQuantile might show the worst offenders.

**Comment by florianhartig** [comment]
Hi Tahsin,

as @Istalan said, the first thing would be to show the standard plot(res) and plot residuals against the predictors. I would recommend to use the plotResiduals function, not testQuantiles. 

It would also help to know what kind of model you are fitting.

**Comment by Tahsin1990** [comment]
Dear all,

Thanks a lot. I plotted the residuals of the full model against each individual covariate. I have attached a figure here. I think this plot does not show heteroscedasticity, as there is less deviation and combined adjusted quantile test is not significant.
Am I right? Thanks again.

![plot](https://user-images.githubusercontent.com/83094821/120734239-c80ee780-c4a5-11eb-9f87-3438979b6be3.png)

**Comment by florianhartig** [comment]
Hi Tahsin, without knowing what kind of model you are fitting here, we can't help you! I would need at least

- your model R code
- main DHARMa plot + res ~ predictors for all predictors

**Comment by Tahsin1990** [comment]
Hi Florian,

I am fitting a zero inflated beta distributed generalized linear linear mixed model using glmmTMB. I want to fit varying dispersion beta glmm as my main DHARMA plot show heterscedasticity. The response variable for my model is prop.abundance. I want to see the effect of urine cortisol and other covariates on prop.abundance. The R code for my model is:
m1.f <- glmmTMB(prop.Abundance ~   urine_cortisol + sex + gestage_b + delivery_mode + maternal_delivery_abx + maternal_corticosteroids + maternal_delivery_magnesium + stool_pma + mbm_cat_week + formula_regular_cat_week + parenteral_week  + pokes_urine_day + antibiotic_dot100 + probiotics_dot100 + glucocorticoids_dot100 +
                  fentanyl_morphine_dot100 + SNAPPEII+(1|study_id), data=bloom1,ziformula= ~1, family=beta_family() )


The main Dharma plot is here:

![Main plot 1](https://user-images.githubusercontent.com/83094821/120836364-b9b2e100-c522-11eb-8c35-8fed468be9a1.png)

It seems there is heteroscedasticity in the model. So I have to know which variable should I include in my dispersion model.That's why I plotted residual vs predictor for all predictors. I have attached here some of the plots for covariates.

![Rplot urine_cortisol covariate](https://user-images.githubusercontent.com/83094821/120841755-23ce8480-c529-11eb-8e20-bd9761eb7342.png)
The above plot is for the covariate urine cortisol, which seems there is homoscedasticity in the model, and also combined adjusted quantile test is not significant.So, this is not heteroscedastic.
![Rplot covariate stool_pma](https://user-images.githubusercontent.com/83094821/120843150-fe427a80-c52a-11eb-8c40-5736725904ac.png)
![Rplot probiotic covarite](https://user-images.githubusercontent.com/83094821/120843182-08647900-c52b-11eb-847e-f186db581e02.png)

Now I have added here residual vs stool_pma and probiotic plot respectively. The adjusted quantile test is not significant and there is much deviation from theoretical quantile for these two plots. So, the above two plots are heteroscedastic.

![Rplot mbm-cat week](https://user-images.githubusercontent.com/83094821/120843748-b53ef600-c52b-11eb-9761-12370a1619b7.png)


The above plot seems homoscedastic and also the levene test for homogeneity of variance is not significant.

After adding appropriate covariates (for which model shows heteroscedasticity) in the dispersion model, the main plot is:
![Rplot with varying dispersion model](https://user-images.githubusercontent.com/83094821/120843992-0353f980-c52c-11eb-820d-f6a64ac8da32.png)

The above plot seems homoscedatic to me. Also, the combined adjusted quantile test is not significant.

Are my interpretations correct? Thanks a lot.

**Comment by florianhartig** [comment]
Hi Tahsin, 

I'm sorry for the late reply, I forgot to answer here and just found the question again going through open issues. 

I would say that the plots are not particularly worrisome, but there is a slight dispersion problem which could be modelled by activating dispformula in glmmTMB (see help for details)

Best,
F

**Comment by Tahsin1990** [comment]
Thanks a lot Florian!
