### ISSUE TITLE
DHARMa  and occupancy model fit

### ISSUE THREAD

**Issue by fieldofhats** [florianhartig/DHARMa#290]
Hello,

I hope this is an ok place to ask a general DHARMa questions, I was redirected here while reading some DHARMa questions on crossValidated..

I have a couple of questions about occupancy model fit evaluation with DHARMa:

I am working with the following occupancy model framework using Bayesian methods,

z(i) ~ bern(w(i))

w(i) = logistic regression of site covs

y(i,j) ~ bern(z(i) * p(i,j))

P(i,j) = logistic regression on replicate covs

and z = true occupancy state, w = occupancy probability, p = detection probability, y = observation data
y(i,j) has been converted to a vector and accounted for with indexing.

Q1: When making the dharma object using createDharma what is the appropriate output to use for the fittedPredictedResponse?
I think using the z * p (posterior median outputs) should work but would like to know what others with more expertise think.

Q2:  it seems straightforward to evaluate the replicate covariates using DHARMa, for instance using plotResiduals, since those variables have the same length as the y data, but I was wondering what the best way to evaluate the site covariates (on w, in the first level of the model).  Maybe createDharma using z median posterior outputs as data, simulations of z, with  posterior medians of w as the fittedPredictedResponse, then look at the covs on w using plotResiduals?  or maybe the data should be y collapsed to 1/0 observations by site?  

Thank you,
Brian

**Comment by florianhartig** [comment]
Q1:  Note that this variable is only used as the x axis in the res ~ pred plot. In principle, you could supply anything that you want your residuals plotted against, there is no single appropriate choice, it's basically just the default predictor for residual patterns. In the case of occupancy models, reasonable choices might be posterior median occupancy, or posterior median observations. 

One point to note though is that you should ideally use an unbiased quantity, which is the reason why you should predict unconditional on fitted REs (see #43)

Q2: I'm not quite sure what you mean by "site covariates" - if you want residuals per site, you should use recalculateResiduals() to aggregate per site, and the look at residuals per site, spatial autocorrelation and all that. If you want to look at residuals within site, you should run plotResiduals(res ~ site), and if site is a categorical variable, this should run KS tests per site (to test within-site fit).

**Comment by fieldofhats** [comment]
Hi Florian,

Thank you, this is super helpful, I am slowly figuring this out.  Ill try to implement your suggestions.

Brian

**Comment by florianhartig** [comment]
OK, great. Note also comments in https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMaForBayesians.html
