### ISSUE TITLE
How to interpret this message `within group deviations from uniformity significant`

### ISSUE THREAD

**Issue by IhsanKhaliq** [florianhartig/DHARMa#291]
Hi Florian,
What does this diagnostic test mean? Does it mean a poor fit? Thanks 

Here is my model
mod4 <-
  glmmTMB(
    total_lesions ~  total_rain + rain_duration  + wind_speed + (1|rainfall_event), family = nbinom1,
    data = dat
  )

![simulate-residuals-1](https://user-images.githubusercontent.com/54728693/124539223-6359fa80-de60-11eb-9891-af0b4f8c4814.png)

**Comment by florianhartig** [comment]
Well, the test alerts you to the fact that there are some within-group residual distributions that are not uniform, i.e. if you plot your residuals for a specific group (which is the one highlighted in red), they don't look uniform -> deviate significantly from your model assumptions. 

The test is corrected for multiple testing, so you should assume that this is systematic; nevertheless, given that this is only one group, it seems to me that this is not a major problem, especially given that your data doesn't seem to be particularly large. I would maybe plot the residuals per group, in particular for your red group, to see if there is an obvious problem, missing predictor etc. and if you don't see anything ignore the problem.

**Comment by IhsanKhaliq** [comment]
Thanks Florian
