### ISSUE TITLE
error message testZeroInflation & testDispersion in poisson model

### ISSUE THREAD

**Issue by Jumoe5** [florianhartig/DHARMa#294]
Hi dear all, Hi florianhartig
I`d like to test a poisson model for overdispersion with DHARMa but got following error message:

testDispersion(glmm1b)
Error in securityAssertion("Simulation from the model produced wrong dimension",  : 
  Message from DHARMa: During the execution of a DHARMa function, some unexpected conditions occurred. Even if you didn't get an error, your results may not be reliable. Please check with the help if you use the functions as intended. If you think that the error is not on your side, I would be grateful if you could report the problem at https://github.com/florianhartig/DHARMa/issues 

 Context: Simulation from the model produced wrong dimension

The DHARMa version is 0.4.3
This is how the model looks like:

```
glmm1b<- glmer(Counts_Peeringevents ~  factor(Class_Party2)  + TSA_Month_Total + 
offset(log(total_bouts_in_party)) + (1|Dyad_ID), family = poisson, data = TUAassocArrival)
summary(glmm1b)
emmeans(glmm1b, list(pairwise ~ Class_Party2), adjust = "tukey")

testZeroInflation(glmm1b)
testDispersion(glmm1b)

```
I am a beginner in R and am just beggining to learn basic principles. 
It would be great to hear your suggestion, how i could fix it. Would you need any more information on this?
Very gratefull for help and advice, 

Thank you
Julia

**Comment by florianhartig** [comment]
Would it be possible to share the data so that I can reproduce the error?

**Comment by Jumoe5** [comment]
Hi Florian, 
Thank you so much for your quick reply!
Here goes the data: 
[1-Rolemodel Choice TUA_20210715_GITHUB.txt](https://github.com/florianhartig/DHARMa/files/6821604/1-Rolemodel.Choice.TUA_20210715_GITHUB.txt)

**Comment by florianhartig** [comment]
Can you additionally give me the code you use to read in your data, or an Rdata file. The structure of your raw data file is a bit unusual, I want to make sure we're using the same dataset.

**Comment by Jumoe5** [comment]
Sry, here it comes
[R code for florianhartig.txt](https://github.com/florianhartig/DHARMa/files/6823279/R.code.for.florianhartig.txt)

**Comment by florianhartig** [comment]
This doesn't work for me. Are you sure this is running through on your computer? Anyway, maybe it's easiest if you give me the data object TUAassocArrival as an Rdata file or via dput.

**Comment by Jumoe5** [comment]
[1-Rolemodel Choice TUA_20210715.txt](https://github.com/florianhartig/DHARMa/files/6824892/1-Rolemodel.Choice.TUA_20210715.txt)

Sorry, somehow the table consistet of only 1 variable- I send yout the data again, and the script as a txt.file I hope that is ok? . 
Again, thank you so much for your effort! 

[1-Role model R script.txt](https://github.com/florianhartig/DHARMa/files/6824909/1-Role.model.R.script.txt)

**Comment by Jumoe5** [comment]
Sry I didnt mean to close this.

**Comment by florianhartig** [comment]
I'm not confident that your data is read in correctly. From a quick look it seems you frequently have characters in the numeric variables of your data file. You are coercing everything to the data type you want, but this will not always work. You should set Na strings when you read in, or correct your data file. 

Anyway, even so, I don't get an error with your script. With all unnecessary code removed, this is what I'm running, and DHARMa output seems to work fine:

```
library(lme4)
library(DHARMa)

TUAassocArrival<- read.delim(dec=",","~/Downloads/1-Rolemodel.Choice.TUA_20210715.txt", header = T)
str(TUAassocArrival)

TUAassocArrival$Class_Party<- as.factor(paste(TUAassocArrival$Class_Party))
TUAassocArrival$Class_Party2<- as.factor(paste(TUAassocArrival$Class_Party2))
TUAassocArrival$Class_Male<- as.factor(paste(TUAassocArrival$Class_Male))
TUAassocArrival$Sex_Party<- as.factor(paste(TUAassocArrival$Sex_Party))
TUAassocArrival$Observer_male<- as.factor(paste(TUAassocArrival$Observer_male))
TUAassocArrival$Dyad_ID<- as.factor(paste(TUAassocArrival$Dyad_ID))
TUAassocArrival$Site<- as.factor(paste(TUAassocArrival$Site))

TUAassocArrival$TSA_Month_Total<- as.numeric(TUAassocArrival$TSA_Month_Total)
TUAassocArrival$Present_Month_Area<- as.numeric(TUAassocArrival$Present_Month_Area)
TUAassocArrival$year_in_area<- as.numeric(TUAassocArrival$year_in_area)

TUAassocArrival$Counts_Peeringevents<- as.numeric(TUAassocArrival$Counts_Peeringevents)
TUAassocArrival$total_bouts_in_party<- as.numeric(TUAassocArrival$total_bouts_in_party)

TUAassocArrival$X0m<- as.numeric(TUAassocArrival$X0m)
TUAassocArrival$X.2m<- as.numeric(TUAassocArrival$X.2m)
TUAassocArrival$X.5m<- as.numeric(TUAassocArrival$X.5m)
TUAassocArrival$X.10m<- as.numeric(TUAassocArrival$X.10m)
TUAassocArrival$X.50m<- as.numeric(TUAassocArrival$X.50m)

glmm1b<- glmer(Counts_Peeringevents ~  factor(Class_Party2)  + TSA_Month_Total + offset(log(total_bouts_in_party)) + (1|Dyad_ID), family = poisson, data = TUAassocArrival)

testZeroInflation(glmm1b)
testDispersion(glmm1b)
```

**Comment by florianhartig** [comment]
No worries, I'm glad it runs now!
