### ISSUE TITLE
testQuantiles(simulationOutput) warning: "We had to increase `err` for some of the quantiles."

### ISSUE THREAD

**Issue by biellia** [florianhartig/DHARMa#300]
Dear Florian,

I am fitting a log(gamma) model using glmmTMB. When I run `testQuantiles(simulationOutput)` I get the following message:

"We had to increase `err` for some of the quantiles. See fit$calibr$err
qu = 0.75, log(sigma) = -3.812583 : outer Newton did not converge fully.
qu = 0.75, log(sigma) = -3.158064 : outer Newton did not converge fully.
Unable to calculate quantile regression for quantile 0.75. Possibly to few (unique) data points / predictions. Will be ommited in plots and significance calculations."

The plot looks fine and I do not need p-values, so I was wondering if I can ignore this message. I am happy to provide more info/plot if needed.

Thanks,

Alessandra

**Comment by florianhartig** [comment]
Hi Allesandra,

these are error messages / warnings from the qgam package, which is used to calculate the quantile lines on the res ~ pred plot. As the error says, the 0.75 quantile line couldn't be calculated and was therefore omitted. 

If the residuals look fine, you can ignore this message.

F
