### ISSUE TITLE
Error when fitting glmmTMB model with fixed random effect variance

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#303]
From a user:

> I get the same error message when running the testDisperson and simulateResiduals functions on my fitted glmmTMB models: "Error in f(x, order = 0) : Wrong parameter length."
> 
> I suspect this is because the glmmTMB models I'm using are somewhat atypical in that I assign a large, fixed value for the variance of the random intercept term following Muff et al. (2019; attached). 
> 
> To give you more background, I'm analyzing used-available for a study of the effects of landcover, topography, and energy infrastructure on within home range (3rd-order) resource selection. Models include a random intercept term by individual-year (Stratum_ID; used and available locations are spatially and temporally matched by individual and year) and a random slope term for energy infrastructure variables by individual (Bird_ID). However, I assigned a large, fixed variance value to the random intercept term for stratum, both to avoid having to estimate separate intercepts for a large number of strata and to prevent shrinkage of stratum-specific intercepts to the overall mean that can bias estimates of fixed-effect parameters and variances (Muff et al. 2019).
> 
> Here is an example of the R code I'm using for glmmTMB models testing the effects of landcover + topography + infrastructure (in this case, % anthropogenic infrastructure cover within 1 km).
> 
> # set up the model structure, but don't fit the model yet
> glmm.VEGTOPO_AnthroA1K.tmp = glmmTMB(USED ~ SD100 + FOR100 + MTNS100 + XERICBARREN100 + TRI100Z + DEV2KZ + DEV2KZSQ + AnthroA1K + (1 | Stratum_ID) + (0 + AnthroA1K | Bird_ID), family=binomial(), data=rsf.females, doFit=FALSE, weights = weight)
> 
> # set the variance of the random intercept term for stratum to a large, fixed value
> glmm.VEGTOPO_AnthroA1K.tmp$parameters$theta[1] <- log(1e3)
> 
> # adjust the number of parameters
> nvarparam <- length (glmm.VEGTOPO_AnthroA1K.tmp$parameters$theta)
> glmm.VEGTOPO_AnthroA1K.tmp$mapArg <- list(theta=factor(c(NA, 1:(nvarparam-1))))
> 
> # fit the model and summarize the model results
> glmm.VEGTOPO_AnthroA1K = glmmTMB:::fitTMB(glmm.VEGTOPO_AnthroA1K.tmp)
> summary(glmm.VEGTOPO_AnthroA1K)
> 
> I think the error I'm getting in DHARMa is because I set the variance of the random intercept term to a large, fixed value (but maybe it's something else?).

**Comment by florianhartig** [comment]
Hi, could you check 

a) if simulate(yourModel) works?
a) if you use the latest version of glmmTMB - I remember that there was a similar issue with glmmTMB lately, and they had fixed something on the glmmTMB side.

**Comment by florianhartig** [comment]
Reply:

> I updated R to version 4.1.1 and updated all packages, including glmmTMB (1.1.2) and DHARMa (0.4.3).
> 
> I then fit the model setting the variance of the random intercept term to a large, fixed value.
> 
> When I ran the simulate() function, it generated no error message(s) and produced an object with the same number of rows as my input file and two columns (sim_1.1 and sim_1.2) with 1's and 0's, so it looks like that worked.
> 
> However, when I run simulateResiduals() on the model, I get the same error as before ("Error in f(x, order = 0) : Wrong parameter length.").
> 
> To confirm that fixing the variance of the random intercept is the problem, I re-ran the same model without setting the random intercept term to a fixed value (I allowed it to be freely estimated). Once I did that, simulateResiduals worked.
> 
> Considering Muff's recommendation re: dealing with random intercept terms in both RSFs and SSFs, I suspect fixing the random intercept variance may become more commonplace when using GLMMs, so it would great to figure out a work-around in DHARMa if possible.

**Comment by florianhartig** [comment]
OK, I have identified the problem, which is that the glmmTMB predict function doesn't support population-level predictions via re.form = ~0 when the REs are not all estimated. Reproducible code is here https://github.com/florianhartig/DHARMa/blob/master/Code/DHARMaIssues/303.R

In my opinion, this is not a DHARMa but a glmmTMB problem, which is why I will file an issue over at glmmTMB. 

Suggested workaround: I have to say that I don't understand why you want to do this anyway - if you set your RE variance large, you essentially making this a fixed effect model. So, why don't you just make the RE with the large variance a fixed effect?

**Comment by florianhartig** [comment]
Over at glmmTMB, @bbolker has suggested an alternative coding for your model which makes the predict function work. See https://github.com/florianhartig/DHARMa/blob/master/Code/DHARMaIssues/303.R

There is an issue remaining, however: at the moment, glmmTMB can simulate data only unconditional, i.e. when simulating, it will create new REs values based on the specified variance. As you set the variance by hand, however, the implemented variance doesn't fit to your model. Thus, the DHARMa residuals (at least in my tests) tended to suggest misfits, while a model that estimates the variance worked fine (see https://github.com/florianhartig/DHARMa/blob/master/Code/DHARMaIssues/303.R). 

The only solution I would have for this is to move to lme4, which allows to simulate conditionally, but I'm not sure if you can set the variances in lme4 in the same way. Maybe @bbolker can comment on this. @jmsigner, this may be also of interest to you?

**Comment by bbolker** [comment]
There's a long discussion [here](https://github.com/glmmTMB/glmmTMB/issues/744) about precisely this issue - how to set up these conditional models using `glmer`. It's trickier/more complicated than with `glmmTMB`, but not impossible. Contemplating spending some time writing some wrapper code to make it easier.

**Comment by florianhartig** [comment]
Thanks Ben! 

I would add that the other option would of course be to simply use a fixed effect for these terms, and then calculate the population mean post-hoc. It's a bit tricky technically, but can be done, see e.g. https://www.biorxiv.org/content/10.1101/2021.05.03.442487v2

**Comment by bbolker** [comment]
The only potential complication/adjustment to this that I can see is that for practicality you probably need to be generate a sparse fixed model matrix (which glmmTMB can do, but glmer **still** can't [many years ago it could but then the architecture changed]); otherwise, if you have `f` levels of the grouping variable and `n` observations, you end up with a model matrix of order `n*f` (usually bad news).

**Comment by florianhartig** [comment]
Hi Ben, many thanks again! OK, I will wrap this up. Let me shortly summarise:

- The issue here arises because the REs are "misappropriated" to implement a hardly regularised population-level estimate for a grouping factor.
- I agree with the OP that this is an interesting re-interpretation of the REs, and I could imagine beyond that, it would also be possible to use this technique to create regularised shrinkage estimators (with shrinkage being controlled via the RE variance) in this way.
- This idea can be easily implemented in glmmTMB, and the approach that is suggested by Ben (see above) is preferable over the OP's code, because it avoids problems in the glmmTMB::predict(), but a fundamental limitation of glmmTMB in this case is that glmmTMB can not (yet) condition on fitted REs, meaning that data-simulations will be created including the hand-specified variances. This means that glmmTMB models fit in this way should not be checked with DHARMa in the standard way. 

Suggested work-arounds

- fit the same model with lme4 (see above)
- fit the RE as a fixed effect, and calculate population-level estimates post-hoc (see https://www.biorxiv.org/content/10.1101/2021.05.03.442487v2)
- create conditional simulations by hand (by first doing conditional predictions, which is possible, then simulate, then use the createDHARMa function)

I have demonstrated option 1-2 in https://github.com/florianhartig/DHARMa/blob/master/Code/DHARMaIssues/303.R
