### ISSUE TITLE
Interpretation of simulated and observed residuals in plot produced by testDispersion

### ISSUE THREAD

**Issue by saverymax** [florianhartig/DHARMa#305]
I have what I think is a fairly simple question. If it has already been asked/answered in a different issue or online elsewhere, please point me to it. Regardless, I have fit a poisson model with the glm function. Then, running testDispersion, the following figure is generated, indicating overdispersion, as well as providing a significant p-value in the test. 

![sim_residuals](https://user-images.githubusercontent.com/29262273/130326974-f68d435e-80f1-4fb1-b552-e6f322756b6a.jpeg)

Here is my question, though I feel a bit silly asking: By default, when refit=F, (From ?testDispersion: "If refit = F, the function uses testGeneric to compare the variance of the observed residuals against the variance of the simulated residuals via their ratios."), what are the observed residuals and what are the simulated residuals? In my case of using the Poisson glm model, are the observed residuals the observed Pearson residuals, and by "simulated residuals", do you refer to the DHARMa residuals? If this is the case, why is it acceptable to compare their variances (pearson vs simulated)? Would you expect their distributions to be asymptotically the same?

Thank you for clarifying this for me!

**Comment by florianhartig** [comment]
Hello,

no, the observed residuals are the observed raw residuals, so it's var(obs - predicted), red line in your plot, and the simulated are var(obs - simulated), histogram in your plot.

Neither DHARMa nor Pearson residuals are used in this particular test, although the amount of overdispersion in your case should be high enough to be visible both in main DHARMa residual diagnostics, by a S-shaped pattern in the QQ plot and a significant deviation of the quantile lines in the res ~ pred plot. 

The reason why the test doesn't use Pearson residuals is that this is only possible if Pearson residuals are available, i.e. there must be an analytical expression for the expected variance, which is not available for all models. 

The reason for the extra test is that it is more sensitive (powerful) than looking at QQ plots or the res~pred plot, and it specifically targets dispersion, while the former react to all kind of residual patterns.

**Comment by saverymax** [comment]
Thank you for the rather quick response, that clears it up for me. It was certainly possible to detect overdispersion in the other diagnostics as well.

**Comment by florianhartig** [comment]
Great! F
