### ISSUE TITLE
Interpretation of Negative Binomial GLMM residuals

### ISSUE THREAD

**Issue by ajw11** [florianhartig/DHARMa#312]
Good evening,

I have fit a negative binomial glmm to a data set with around 200 observations. I do not have the residual plot readily available so I've superimposed my results onto a previous result. The red lines represent the pattern in my output. Any advice would be much appreciated. There are no issues with dispersion of KS test, (although the KS test is only marginally over .05), but the residual pattern (negative linear relationship) appears to be an issue. Any advice would be much appreciated.

![Picture1](https://user-images.githubusercontent.com/87678321/137217438-f316adb6-81db-43cf-87f6-821f0fbaa66f.png)

Thank you!

**Comment by florianhartig** [comment]
What the plot tells you is that your model underestimates for low predicted values and overestimates for high predicted values.

Any number of things might be the reason, it's hard to say without seeing either your plots or your model.
