### ISSUE TITLE
Outlier test/Inferences for mixed models (question)

### ISSUE THREAD

**Issue by ajw11** [florianhartig/DHARMa#318]
I have a glmm that I have fit to a data set whose residual diagnostics (KS test, overdispersion, and residual vs. predicted values) look OK except for the outlier test. I read through the DHARMa pdf 
(https://cran.r-project.org/web/packages/DHARMa/DHARMa.pdf) and I see you reference the paper "Pinho, L. G. B., Nobre, J. S., & Singer, J. M. (2015). Cook’s distance for generalized linear mixed models" to check if the outliers are influential.  

I found the R code referenced in the paper for calculating the glmm Cook's D, but it only works for 'merMod' objects, and I am using glmmAdaptive because I want the marginalized coefficients that this package offers.  Another option from the aforementioned pdf on DHARMa is to remove the outliers from the model, which I have tried. When I do this the residual diagnostics are much worse, which to me implies the outliers should stay in the model. I do not have the output and data available unfortunately, but wanted to get your opinion on what else you should look for in the model when the outliers are removed to get a sense of whether to keep them in or not.  In this case, I am only interested in the inferences, not prediction. Thank you!

**Comment by florianhartig** [comment]
Hi,

if the residuals look fine regarding all other aspects, and you have already set the number of simulations high (as noted in the help), I wouldn't be too concerned about this. As noted in the help as well, the test statistics for the default outlier test is not exact and can be anti-conservative in some cases (if this applies to your model, you should have gotten a warning asking you to switch to the more computationally expensive test based on the bootstrap). 

As also noted in the help, DHARMa currently doesn't tell you how far these values our outside the distribution. Maybe I could implement some guidance regarding that, either on the simulated distribution, or on the likelihood, but at the moment, you just know that these points COULD be concerning, not that they ARE.

If you want to be 100% sure, you could simply check if model results change if you drop these values. 

Best,
Florian

**Comment by ajw11** [comment]
Thank you!
