### ISSUE TITLE
Allow plot title customization 

### ISSUE THREAD

**Issue by Nelson-Gon** [florianhartig/DHARMa#320]
Hi,

Thank you for this awesome package that makes model diagnostics more interpretable. I would like to request for a feature that allows customization of the `main` (title) of the plot produced.

```
my_glm <- glm("mpg ~ disp",data=mtcars)
simulated = simulateResiduals(my_glm, plot=FALSE)
plot(simulated, main="test")
```

The above will not work as expected, it will produce:

![image](https://user-images.githubusercontent.com/42792514/145819391-dc718137-ccd5-4e99-a723-ed63a62ec6e0.png)

I looked at the [code](https://github.com/florianhartig/DHARMa/blob/648f13bb25361c402fceeb3c30e0be4f2931d04a/DHARMa/R/plots.R#L33) and this line is particularly hard to [customize](https://stackoverflow.com/questions/7101665/removing-text-added-to-a-plot-with-mtext).

```
 mtext("DHARMa residual diagnostics", outer = T)
```

What I would love to do is to maintain the title generated with `mtext` but also allow for a custom title. This would be useful for example if I have multiple models in a list and want to auto paste what formula each model used. (I can PR with a suggested way if possible).

Thank you,

NelsonGon

**Comment by florianhartig** [comment]
Hi Nelson,

thanks for reporting this, and sorry for the late reply. Yes, should be possible to solve this, I'll have a look!

F

**Comment by florianhartig** [comment]
OK, what I have done now (development version) is that 

my_glm <- glm("mpg ~ disp",data=mtcars)
simulated = simulateResiduals(my_glm, plot=FALSE)
plot(simulated, title="test")

produces 

<img width="704" alt="image" src="https://user-images.githubusercontent.com/5457753/149123296-a3ff241d-5dc8-498a-a001-4bd332da88d0.png">

Is that what you wanted?

**Comment by Nelson-Gon** [comment]
Yes, this is what I wanted. Basically to just add some title above the plot and leave the rest intact (The Combined adjusted quantile part I think is probably better left intact).  Here, I would for example add the title 

```
paste0( c("Diagnostic plot for ", "mpg~disp")) 
```
The idea was that I had created a list of plots and was unable to tell the reader which was which.

**Comment by florianhartig** [comment]
OK, this is now on GitHub, if you want to install it follow instructions on https://github.com/florianhartig/DHARMa. This will go to CRAN with 0.4.5 in the next days!
