### ISSUE TITLE
Support for survey-weighted models from svyglm and svy_vglm

### ISSUE THREAD

**Issue by symbalex** [florianhartig/DHARMa#321]
I work a lot with weighted complex survey data and as far as I can see, there's little support (in general) for regression diagnostics for generalised linear models fitted with `survey::svyglm` and more advanced models such as hurdle etc. from `svyVGAM::svy_vglm`. Is it possible to introduce `DHARMa` support for these? 

I was wondering if it'd be possible to combine `DHARMa`'s simulated residuals with some of the standard survey weight visualisation methods, for example:

- fit a VGLM using `svyVGAM::svy_vglm`
- like the standard `DHARMa` method, for each observation point simulate values from the fitted model, calculate the ECDF and generate the simulated residuals (VGAM has the full set of random generation functions for each distribution so it should be possible)
- but when plotting, use a survey weight visualisation methods such as [alpha-blending](https://projecteuclid.org/journals/statistical-science/volume-32/issue-2/Fitting-Regression-Models-to-Survey-Data/10.1214/16-STS605.full) or [bubble plots](https://commons.wmu.se/cgi/viewcontent.cgi?article=1001&context=lib_chapters) or doing inverse probability plots, and fitting the quantile regressions with weights.

Thank you!

**Comment by florianhartig** [comment]
Hi Alex,

thanks for the suggestion. I would separate the question into 2 separate points:

1. Can I add DHARMa support for VGAM and svyVGAM: upon a very superficial check, it seems to me that VGAM (and based on this svyVGAM) do include a simulate function, although it may be that the simulation function is not implemented for all model classes (ZIP models with svyVGAM didn't work, for example). Nevertheless, it seems to me that including these model classes into DHARMa is technically possible (maybe with limitations). One open question for me on this is how the survey weights work exactly - for DHARMa to make sense, there needs to be a data-generating process that one can simulate from. Simple likelihood weights n GLMMs typically break this property. I have no experience with VGAM and svyGAM, so I have to read up how the survey weights are treated in the models and if the weights result in a likelihood (= data-generating model exist) or in a pseudo-likelihood. I have opened a new issue here https://github.com/florianhartig/DHARMa/issues/322, if you have any insights on this feel free to comment there. 

2. The second question is if I can / should include additional plots. Here, I wasn't really sure if it makes sense to implement anything in DHARMa, given that you can easily extract residuals from a DHARMa object, i.e. people can just plot. the plots that you show themselves? I would probably only implement additional plots in DHARMa if they are very generally useable (i.e. for all regressions, beyond VGAM). If you have good ideas on what those plots would be, feel free to comment. Additionally: if there are existing R packages that perform the plots that you want to do, it would probably be possible to report DHARMa results in a way that they can be used with these packages. For this, however, I would need to see the code.

Cheers,
Florian

**Comment by symbalex** [comment]
Hi Florian, thanks for the response

Re point 1, I know that an underlying assumption is that the population being surveyed derives from a realisation from a probability model with some density function. But I don't currently have the depth of knowledge to answer your question. I will get back to you if I find out more :)

Re point 2, good idea - I doubt they would have a general use case. Probably the best way to start is me to do some research and if it looks promising, go off do it myself using `createDHARMa` as you suggest in #322

**Comment by florianhartig** [comment]
Hi Alex, just for clarification: `createDHARMa()` is for point 1), if you create simulations by hand, once you have the DHARMa object extract residuals using `residuals()` and plot them as you desire. 

Once I have added appropriate interfaces for VGAM, step 1 can be skipped.

**Comment by ZhaoRanze** [comment]
Sorry, could I just interrupt a moment? i am new player，i wanna update R in linux for the “VGAM” package ，could you help me？

**Comment by florianhartig** [comment]
@ZhaoRanze - this is the issue section for the development of the DHARMa package. For general questions about R, have a look at the usual forums, e.g. https://stackoverflow.com

**Comment by florianhartig** [comment]
@symbalex - if you think that there is no need to implement special plots in DHARMa (just VGAM and svyVGAM support), feel free to close this issue. Else I'm happy to entertain ideas for new plots here. As I said, as a prerequisite for being included directly in DHARMa, the plots should be generally useful, i.e. applicable beyond VGAM and a very specific design.

**Comment by symbalex** [comment]
Thanks Florian. I don't think there is a need to update for special plots since I don't think it will have a general use. Thank you for your input!
