### ISSUE TITLE
Underdispersion and residuals clustered around 0

### ISSUE THREAD

**Issue by sssiv93** [florianhartig/DHARMa#353]
Hi Florian,

Thank you for this great package!

Are you able to provide any insights/recommendations as to what might be causing my model diagnostics below? 

I am fitting a negative binomial regression on a dataset of 856 entries, with 10 features. It models customers, as a function of company, product type, log(spend) and market demand. I can see underdispersion and a pattern of residuals clustered around 0.00. 

![Screenshot 2022-11-08 at 17 23 58](https://user-images.githubusercontent.com/107478029/200633253-19a16cf6-805a-46f6-ae5f-98011a507ecf.png)

For reference, I tried fitting a poisson regression before this and saw significant overdispersion:

![Screenshot 2022-11-08 at 17 25 50](https://user-images.githubusercontent.com/107478029/200633634-c0fbb8ae-19b9-4515-a20d-951b8a765d79.png)

**Comment by florianhartig** [comment]
Hello,

I'm sorry, I thought I had responded but it seems I didn't. It seems that there is a substantial number of data points for low model predictions for which the model under predicts.

![image](https://user-images.githubusercontent.com/5457753/203087405-e71211ec-bbcc-4178-add4-3e415ecb71cb.png)

Looks like a strong case of zero-inflation to me, i.e. you have observations that are zero, or else you get relatively high counts.
