### ISSUE TITLE
Interpreting DHARMa output

### ISSUE THREAD

**Issue by anaverahrami** [florianhartig/DHARMa#374]
Hi folks,

I'm working with a binomial, logistic regression model using the glmer function from lme4. I'm interested in looking at the diagnostics of my top model and have run code using DHARMa to look at my residuals with one of my factor variables (HabitatType.f) since I know the package is useful for GLMMs. At first, I ran my code as the below with refit = F and produced the below outputs:
res <- simulateResiduals(mod.top, plot=T, refit = F)
par(mfrow = c(1,3))
plotResiduals(res, diel_sub$HabitatType.f)
testDispersion(res)
testZeroInflation(res)

![mod top_withoutBootstrap_diagnostics](https://user-images.githubusercontent.com/129873027/229826702-449cafe3-28d2-4b06-b29f-74207be43db3.png)
![mod top_withoutBootstrap_diagnostics2](https://user-images.githubusercontent.com/129873027/229826703-bd10269c-c792-400e-928a-ebe5e475a077.png)

But because I am using a random effect of "site", I chose to change refit to T to conduct bootstrapping and got the following outputs:
![mod top_withBootstrap_diagnostics](https://user-images.githubusercontent.com/129873027/229826917-3c085258-e9de-4b90-9439-43594a8d09e7.png)
![mod top_withBootstrap_diagnostics2](https://user-images.githubusercontent.com/129873027/229826920-2d154f91-c5fd-4d47-84ca-c85512d6d6aa.png)

I don't have any experience interpreting these plots for GLMMs and was hoping someone could help me with the interpretation. I see that when I use bootstrapping, my QQplot line is much closer to the expected line, but the p-values for the KS test, Dispersion test, and Outlier test are all significant whereas without bootstrapping, my QQplot line is more varied from the expected and only the outlier test and KS test have significant p-values. 

Also as I mentioned, I am running these residuals against my factor variable of HabitatType which has three levels. But for some reason, both with and without bootstrapping, my figure for the Levene Test for homogeneity of variance is showing a 4th level (unlabeled) and I can't seem to figure out why this 4th level is being produced on the plots. 

Any guidance you can provide would be much appreciated and thanks in advance!

**Comment by florianhartig** [comment]
Hi, sorry for the late reply - could you tell me which model you are fitting as well as roughly what the data size / dimensions are? 

F

**Comment by melina-leite** [comment]
Hi @anaverahrami, do you still have questions about it? 
Given the time that has passed, I will close this issue, but if you still want to discuss it, feel free to reopen it. :)
