### ISSUE TITLE
Overdispersion in a beta regression?

### ISSUE THREAD

**Issue by andres-v-s** [florianhartig/DHARMa#376]
I'm trying to run a beta regression to predict my dependent variable Consistency, which has values between 0 and 1. Here is the distribution of Consistency values in my dataset:

![image](https://user-images.githubusercontent.com/131745241/234192044-86f91457-6952-42aa-8b34-a5229f526540.png)

I originally tried linear mixed models with different transformations, but none of them seemed satisfactory (none of the Q-Q plots looked good), so I decided to try a beta regression, using the following command:

`l_cons <- glmmTMB(as.formula(paste(var_predicted, ' ~ ', paste(effets_model, collapse = ' + '), '+ ', nom_random, sep = '')), data = d, family=beta_family())`
(the model is quite massive with a huge number of predictor variables and interactions, hence this construction rather than adding each predictor variable manually).

Now, I wanted to test if overdispersion might be a problem. First of all, by calling
`summary(l_cons)`

I get
` Data: d
     AIC      BIC   logLik deviance df.resid 
 -6861.3  -6465.1   3499.7  -6999.3     2235 
Random effects:
Conditional model:
 Groups Name        Variance Std.Dev.
 Sujet  (Intercept) 0.04931  0.2221  
Number of obs: 2304, groups:  Sujet, 72
Dispersion parameter for beta family (): 26.5 `

Moreover by calling (from the DHARMa package):
`simulateResiduals(l_cons, plot = T)`

I get the following output:
![image](https://user-images.githubusercontent.com/131745241/234192347-35b41e68-469d-464e-afd5-1127030f4b2b.png)

as well as
`testDispersion(simulateResiduals(l_cons, plot = T))`

with the following output: 

![image](https://user-images.githubusercontent.com/131745241/234192437-ea00adc9-5b6f-4f03-972f-ce6453f4cb6b.png)

Can somebody explain to me what this means? Does it mean that the distribution of my data is altogether unfit for a beta regression? Are there some transformations that should be done? If the conclusion from this information is that there is indeed overdispersion, what does that mean exactly?

**Comment by florianhartig** [comment]
OK, I will consider this closed for the moment, in case you have further questions feel free to re-open the issue!
