### ISSUE TITLE
Seeking Explanation for Residuals vs. Predicted Plot

### ISSUE THREAD

**Issue by ToorSingh** [florianhartig/DHARMa#382]
@florianhartig 

Hi Florian,

I hope you're doing well. I recently conducted an analysis on a set of GLM models (binomial distribution with 0/1 responses) using DHARMa. The results of tests such as the KS test, dispersion test, and outlier test were all non-significant. However, when I plotted the residuals against model predictions, I encountered unexpected patterns. Interestingly, individual plots for each predictor variable showed no issues, and both zero inflation and spatial autocorrelation were also non-significant. Could you provide some insight into this matter? Please feel free to ask me if any other information is required.

Thank you,
Tehlu

Model 1: 
![image](https://github.com/florianhartig/DHARMa/assets/115712839/d9d9b442-a723-4930-a801-a3165231022c)

Model 2:

![image](https://github.com/florianhartig/DHARMa/assets/115712839/27369703-3de2-4b63-837e-8d3561ff93da)

Model 3:

![image](https://github.com/florianhartig/DHARMa/assets/115712839/dce5ab09-978a-4987-9285-1ca21e57112b)

**Comment by florianhartig** [comment]
Hello Toor,

by errors, you mean that there is a pattern in the res ~ pred plot?

What I can say is that your plots don't seem particularly concerning to me - yes there is a slightly wobbly pattern, but given the relatively low number of data points, this could also be random. 

Best, F
