### ISSUE TITLE
Is there a way to directly access or export the plot returned by plotResiduals()? 

### ISSUE THREAD

**Issue by smsfrn** [florianhartig/DHARMa#395]
I'm likely missing something obvious, but the plot itself doesn't appear to be a component in the returned object, so I'm having trouble accessing it to save programmatically. Any ideas?

**Comment by florianhartig** [comment]
Hello Sam, 

can you give me an example of another plotting function where this works?

Note that DHARMa is using base R and and not ggplot for plotting

Best,
F

**Comment by smsfrn** [comment]
Oops, nope. I misremembered what could be done with base graphis. I'll close this!
