### ISSUE TITLE
Adjust DHARMa plots for color blindness

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#413]
I was told that the red-block color scheme in many DHARMa plots is not suitable for color blindness (my bad, didn't realise that red-black is nearly as bad as red-green).

Color-blind people, feel free to comment what the best solution would be. 

For the moment, I think I would maybe move to an option to change signal colours in DHARMa from red to something else (e.g. blue)?

**Comment by florianhartig** [comment]
Maybe do this via options?

**Comment by florianhartig** [comment]
e.g. options(DHARMaSignalColor = "blue")

**Comment by florianhartig** [comment]
Thanks Marius, this would in principle be a perfect solution but our DHARMa red is not "red" (as in R3) and not the 2 in the R4 pallete, and I'm not sure if I like the R4 value 2 ... @melina-leite, maybe you can do a few test plots?

**Comment by florianhartig** [comment]
I think it's saver to got with the options - I'll push the write to options at startup and then access via .Options$DHARMaSignalColor or getOption("DHARMaSignalColor")

**Comment by melina-leite** [comment]
Hi, I substituted the default color and introduced notes on the plot help files. Did some plot tests and it seems to be ok now. :)

**Comment by florianhartig** [comment]
Hi Melina,

I wonder if we should add a note about this in the vignette as well?

Also, in the help of plotResiduals, there it displays for me 

```
> If nObs > 10000, the scatter plot is replaced by graphics::smoothScatter
> 
> #' @note The color for highlighting outliers and quantile lines/splines with significant tests can be changed by setting options(DHARMaSignalColor = "red") to a different color. See getOption("DHARMaSignalColor") for the current setting. This is convenient for a color-blind friendly display, since red and black are difficult for some people to separate.
```

so probably there is a double @note?
