### ISSUE TITLE
Interpreting residual pattern for Gamma GLMM

### ISSUE THREAD

**Issue by melina-leite** [florianhartig/DHARMa#427]
Question via email

> I have been trying to fit a GLMM with Gamma distribution(link=log).  Then I used DHARMa to diagnose the dispersion. It showed an underdispersion.
> To my best knowledge and the histogram below, GLMM with Gamma is the most appropriate model, as the intensity is non-integer.
> 
> Here is my formula:
> gamma_glmm <- glmmTMB(intensity ~ longitude + latitude + route + season + (1 | species) +(1 |  study_id), family = Gamma(link = "log"))
> 
> I paste the  output we obtained from DHARMa below.
> 
> <img width="1172" alt="image" src="https://github.com/user-attachments/assets/8a0c7ebb-d67d-464c-8a58-d0bac3650e39">
> 
> <img width="867" alt="image" src="https://github.com/user-attachments/assets/cc4798c6-4e79-4c6d-aad1-5c7a5b5f19c1">
> 
<img width="913" alt="image" src="https://github.com/user-attachments/assets/5466550f-b61e-4a9c-bbba-ced1731d8192">
> 
> 
> 	DHARMa nonparametric dispersion test via sd of residuals fitted vs.
> 	simulated
> data:  simulationOutput
> dispersion = 2.3656, p-value = 0.016
> alternative hypothesis: two.sided

**Comment by florianhartig** [comment]
Hi,

note that you have **overdispersion**, not underdispersion (red line is higher than simulation envelope). Also, you have very pronounced **heteroskedasticity** (meaning that the dispersion / spread changes with the predicted mean).

It is possible that you could address your problems with the dispersion option in glmmTMB, but I would also consider that Gamma may not be a good distribution for your data. Note e.g. that you have some weird outliers in the residual vs. predicted plot. As I don't know how this data was created, and what the background is, it's hard to say more.

Best 
Florian
