### ISSUE TITLE
Interpreting DHARMa diagnostics for a binomial GAM

### ISSUE THREAD

**Issue by katiarepulles** [florianhartig/DHARMa#429]
Hi Florian, 

I hope this message finds you well. My name is Katia, and I am currently working on my master's thesis at Universitat de Girona (Girona, Catalonia, Spain). I have read the very useful vignette you provided about the DHARMa packages. However, there are still a few points that I'm not certain about and I wish I could ask you directly for advice.

I built a generalized additive model (GAM) to analyze species occurrence as a function of habitat fragmentation, habitat amount and other spatial covariates. The model is as follows:

Modelo_gam <- gam(
  occurrence ~ frag + s(hab_amount) + s(X, Y) + s(SITES, bs = "re"),
  family = binomial,
  data = data2,
  method = "REML")

In this study, "occurrence" represents the binary response variable indicating the presence or absence of the species. The primary predictor is "frag," which represents habitat fragmentation. The model also includes smooth terms for "hab_amount,"representing the amount of habitat,  and for the spatial coordinates "X" and "Y," which were incorporated to account for spatial autocorrelation. Additionally, the model incorporates a random effect for "SITES," which is specified as a smooth term with a random effect basis (bs = "re"). The main purpose of the study is to assess whether habitat fragmentation and habitat amount influence primate species occurrence within patches of forest. 

I ran diagnostics on the model using the DHARMa package:

<img width="693" alt="Captura de pantalla 2024-09-05 a las 19 43 09" src="https://github.com/user-attachments/assets/5f6651b1-8da0-4d0c-b15c-b7d4b1b07337">  
<img width="720" alt="Captura de pantalla 2024-09-05 a las 19 43 28" src="https://github.com/user-attachments/assets/fe394969-d339-46a1-b38b-c53f1925fde3">
<img width="701" alt="Captura de pantalla 2024-09-05 a las 19 43 42" src="https://github.com/user-attachments/assets/babcb8f1-3c1e-4781-9cd3-bf34d6b5c296">

I just wonder if these warnings are severe enough to suggest that this model should not be used. I have an N = 978 landscapes.  The Q-Q plot looks fine, but the highly significant KS test and the red lines in the residual plots are really concerning to me.

Thank you so much for your time. I look forward to your responses.

Best wishes,
Katia R

**Comment by florianhartig** [comment]
Hello Katia,

to add to what Melina said: although significant, the magnitude of the deviation from expectations is very small, as all plots look nearly like they should. So, based on the plots you showed, I don't see any reason to change something about your model. 

However, as Melina suggested, as you seem to have spatial data a test for autocorrelation would make sense, plotting against all predictors would make sense, and potentially grouping spatial would also make sense, as suggested in https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html#binomial-data

Best
Florian

**Comment by florianhartig** [comment]
ps.: although given you fit s(X, Y), it's very unlikely that you have a residual spatial pattern.

**Comment by katiarepulles** [comment]
Hello Melina and Florian, 

Thank you for your responses! I forgot to upload the plot of spatial autocorrelation, but I did the test for autocorrelation in the residuals and I didn't find any autocorrelation.

<img width="577" alt="Captura de pantalla 2024-09-07 a las 9 18 57" src="https://github.com/user-attachments/assets/e767ea0d-bf47-443f-a8a2-a08559acaa1c">

![Autocorrelation_plot](https://github.com/user-attachments/assets/b3d234f8-65bd-45b5-9165-c5a5698be096)
 I’ll take your suggestions into account.

Thanks again for your support!

**Comment by florianhartig** [comment]
Hi Katia,

yes, very likely s(X, Y) will have absorbed any strong spatial pattern that you have.

Again, as I said, unless you find anything in the res ~ predictors and possibly when grouping residuals, I don't see a problem with the model.

I'll close this, as this seems to be resolved. 

Best
F
