### ISSUE TITLE
Include random effects when plotting residuals vs. predicted?

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#43]
When plotting residuals vs. predicted in mixed models, a common question is if predictions should be calculated including the RE terms (conditional) . 

**The answer is no, at least if the REs are also included (re-simulated) when calculating the residuals!** 

The reason is that predictions with REs can produce artifacts (see, also https://github.com/florianhartig/DHARMa/issues/42). To understand this, note first that the question about conditional / unconditional appears both on the x and y axis, i.e. we can calculate residuals and predictions with / without REs. 

So, let's see what happens if we do that - consider this example, where we compare residuals plotted against the unconditional predictions (no REs, DHARMa standard), and the conditional predictions (predictions include REs, lme4 predict standard):

```
    # creating test data according to standard poisson GLMM assumptions
testData = createData(sampleSize = 200, randomEffectVariance = 1.5, family = poisson(), numGroups = 20)

# fitting GLMM
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), family = "poisson", data = testData)

# res ~ pred, with conditional and unconditional predictions
simulationOutput <- simulateResiduals(fittedModel = fittedModel)
par(mfrow = c(2,2))
plotResiduals(simulationOutput$fittedPredictedResponse, simulationOutput$scaledResiduals , main = "Unconditional Residuals\n Unconditional Predictions\n DHARMa standard", rank = T)
plotResiduals(predict(fittedModel), simulationOutput$scaledResiduals, main = "Unconditional Residuals\n Conditional Predictions\n", rank = T)

simulationOutput <- simulateResiduals(fittedModel = fittedModel, re.form = NULL)
plotResiduals(simulationOutput$fittedPredictedResponse, simulationOutput$scaledResiduals , main = "Conditional Residuals\n Unconditional Predictions\n", rank = T)
plotResiduals(predict(fittedModel), simulationOutput$scaledResiduals, main = "Conditional Residuals\n Conditional Predictions\n", rank = T)
```

![image](https://user-images.githubusercontent.com/5457753/38176413-7af7845a-35ee-11e8-9f80-f029eb3db8cd.png)

The effect goes away when specifying the random effect as fixed 

```
# alternative with grouping factor as fixed effect, this removes the pattern with group
fittedModel <- glm(observedResponse ~ Environment1 + as.factor(group), family = "poisson", data = testData)
simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plot(simulationOutput, rank = T)
```

![image](https://user-images.githubusercontent.com/5457753/37997113-4fae0350-321a-11e8-9537-15e54dd96afa.png)

I should add more explanation on this in the vignette, especially as the predict() function in R includes the REs by default, so users will be tempted to plot residuals against predictions with REs. 

There seem to be a few related questions on CV that are still unanswered. 

https://stats.stackexchange.com/questions/89991/use-predicted-values-with-or-without-random-part-to-plot-residuals-with-binnedpl

https://stats.stackexchange.com/questions/89991/use-predicted-values-with-or-without-random-part-to-plot-residuals-with-binnedpl

https://stats.stackexchange.com/questions/325898/strong-linear-pattern-in-residuals-of-random-intercept-model-simulated-unbalanc

**Comment by AmeBol** [comment]
That is something I have been wondering quite some time now. But the answer still leaves me a bit puzzled. Which is now the type of plot that I should use to examine the fit of my model? 

If I use the DHARMa standard, I will miss out on plotting the RE completely.  Why is that the standard, when the RE is an essential part of my model?

**Comment by nabaesjodar** [comment]
Thanks a lot Florian!
I consider my self a begginer, but I also can't get this conditional/unconditional on REs issue, and would appreciate more explicit info in the vignette, both about reasons for use and the use itself. DHARMa is the first time I have ever read about it.

Also, I found some models show exactly the same output plots (QQ and res vs. pred) conditional and unconditional on REs, while other models show very different ones (e.g. one good and one bad)?   Why is that?

Best,
Diego.

**Comment by florianhartig** [comment]
Sorry, I realise I also forgot to answer to @AmeBol, so this is to both

a) @nabaesjodar: for a perfect model, both conditional / unconditional plots should look fine, so in doubt just check both.

b) I have chosen the unconditional as a default for DHARMa, because this checks the RE + the final distribution at the same time (so the entire model structure is re-simulated). If you simulate conditionally, you check the final residuals, conditional on the fitted REs, so you check e.g. only that the residual distribution is Poisson, conditional on the values of the fitted REs. 

c) However, as noted in the help about dispersion tests, in particular dispersion tests are less powerful with unconditional simulations. So I would suggest to do dispersion tests based on conditional simulations (if you regression package permits this)

d) @AmeBol, you can of course additionally plot the RE distribution, as advised in many textbooks, and test for normality (take out REs, make a shapiro.test on them). I have no special functions for this in DHARMa because this is a test not on the residuals, but on the fitted values, so it's completely independent of the quantile residuals that are calculated in DHARMa. It may also be useful to look at REs against predictors or space, as they can absorb misfit (this is again one of the reasons, by the way, to use unconditional simulations as a default, because then you see this misfit in the DHARMa residuals).

**Comment by florianhartig** [comment]
I will add a few clarifications about this in the vignette.

**Comment by florianhartig** [comment]
Looking at this, this is all explained in the vignette already, so I'll close this!
