### ISSUE TITLE
Automatic scaling of x axis for residual plots

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#44]
Would be nice to transform x in a way such that the distribution is more or less flat

**Comment by florianhartig** [comment]
Would require some function that automatically rescales such that the distribution is more or less flat. I tried around with box cox, as in 

```
library(car)

# idea - using box cox transformation on the x data 

par(mfrow = c(1,3))

x = rexp(200)
hist(x)
out = boxCox(lm(x ~ 1))
hist(x^out$x[which.max(out$y)])

# negative numbers don't work at all, but even so, it the distr is right-skewed, it also doesn't really work
x = - rexp(200)
x = x - min(x) + 0.01
hist(x)
out = boxCox(lm(x ~ 1))
hist(x^out$x[which.max(out$y)])

```
which kind of works when x is strictly positive and right-skewed ... not sure if there is better solutions.

The file is in https://github.com/florianhartig/DHARMa/blob/master/Code/Experimental/transformation.R

**Comment by florianhartig** [comment]
If done, add as option to plot, and add warning to plot if x distribution is very uneven -> need to find a good test for the level of "unevenness" - e.g. measure percentage overlap with uniform, but careful with low sample size

**Comment by florianhartig** [comment]
new plan: just plot the rank on the x axis.

Maybe option: if unique values < 10 and > 5 values per unique value, transform to categorical?

**Comment by tqdo** [comment]
Hi, just curious what is the rationale behind rank transformation?

**Comment by florianhartig** [comment]
The rationale is to obtain a homogenous distribution in x. I introduced this option because I noted that residual patterns were poorly visible if x is strongly skewed, and also the quantile regression will be sometimes less reactive to residual patterns in this case. . 

Note that you likely get different p-values of the quantile gams that test for heteroskedasticity depending on the transformation, but via the arguments in https://github.com/florianhartig/DHARMa/issues/365 we expect that residuals should be homogeneously uniform in y direction for ANY grouping of the residuals, and thus for any transformation of x.
