### ISSUE TITLE
Reason for underdispersion in lme4::glmer with Poisson distribution

### ISSUE THREAD

**Issue by christopherDennison** [florianhartig/DHARMa#449]
Hello there!

I hope this message finds you well. I really do appreciate all of the incredible functions available through Dharma.

I have a question RE some results from a glmer model I ran with count data (species richness) using a Poisson distribution.

Specifically, my Dharma plot for testDispersion is as such:

![GLMER(testdispersion](https://github.com/user-attachments/assets/00456ecf-7b82-4149-9307-ef1c16be3dea)
 and the results:

_DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated_

data:  simulationOutput
dispersion = 0.679, p-value < 2.2e-16
alternative hypothesis: two.sided

These results would suggest to me underdispersion (variance less than mean), which is further evidenced by the plot of simulated residuals:

![DHARMA_plot](https://github.com/user-attachments/assets/ac0fce01-7f75-465e-9956-e30f113dbf89)

Now, I understand that some underdispersion can be reasonably ignored, as it indicates conservative inference. However, I thought it would be prudent to ask the experts if they had insight for this humble graduate student.

Thank you so much for your time and support.

- Chris

**Comment by florianhartig** [comment]
Hi Chris,

visually, the underdispersion you have here doesn't appear to be particularly concerning, but in general, underdispersion in a Poisson can arise:

- If your distribution is not Poisson
- If you are overfitting with FE or RE
- If you have zero-inflation 

From the info that you provide, I can't say if that is the case, but I would think about whether your model is really complex, and you could also test if adding a ZI term (glmmTMB) improves the fit.

**Comment by florianhartig** [comment]
Glad it helped - if overfitting is really the issue though, why not make the model simpler? In any case, I'll consider this solved, so will close!
