### ISSUE TITLE
Interpretation of residual plots for Poisson GLMM - overprediction with possible underdispersion

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#45]
From a user: I’m using the DHARMa package, and I obtained this residuals plot

![image001](https://user-images.githubusercontent.com/5457753/35686797-71456c60-076d-11e8-9821-fab2ca69e3a3.png)

I did the tests explained in the vignette :

·         testUniformity : S
·         testOverdispersionParametric : NS
·         testZeroInflation : NS
·         adding overdispersion correction : no change
·         adding quadratic term for both regressor : no change

Can you help me giving a lead about what’s going wrong ?

**Comment by florianhartig** [comment]
Your model seems to predict systematically too high values (note that residuals tend to be more below the 0.5 line, i.e. tend to be more negative than expected). 

Without more details on the model, it's hard to say what's going on. What kind of model are you fitting here?

**Comment by cdv04** [comment]
It's GLMM : global_mod1 <- glmer(Nb_Mammals ~ GeoMean_dose + Bush.cover+ (1| Date/Site), data=tracks_sc, family="poisson").

Do you think it could be because an important predictor is missing, or because of spatial or temporal correlation ? Not tested yet.

Thanks so much for your help
Claire

**Comment by florianhartig** [comment]
The model has an intercept, so the fact that it doesn't use the intercept to simply push the predictions a bit lower suggests to me a problem in the distribution, rather than anything else. Temporal / spatial residual autocorrelation shouldn't produce this problem. Moreover, note (even if the dispersion test was n.s.) that it looks a bit underdispersed. Missing predictor would tend to create overdispersion. 

First of all, I have a question regarding your REs - why do you specify Date/Site nested? You realize that this means a different site effect is fit for each date? This probably only makes sense if you have several observations for every date AND site, but even then it's a bit weird because this creates a quite complex model. 

The reason why I'm asking is that specifying a too complex model can lead to overfitting, which creates underdispersion. So, I'd be curious to know what happens if you specify crossed REs (1| Date) + (1|Site). Of course, you shouldn't use the residuals to guide your RE structure, but in this case that would seem more natural to me. I'm not a fan of model selection on REs, but if you want to formally compare the two options, the best way is to use simulated LRTs (I'm not sure if there is a package for glmer, https://cran.r-project.org/web/packages/RLRsim only supports lmer, probably you would have to do this by hand). If you don't compare via simulation, you have to be very careful - the standard AIC function does't calculate the df for the REs properly, I'm not sure if anova in R would test correctly. 

If that is not the problem, you can try negative Binomial and adding a observation-level random effect, and check residuals against predictors, but as I said, I doubt that is the problem. 

In that case, you can either i) leave the model as it is ii) move to a more flexible distribution for count data, e.g. https://cran.r-project.org/web/packages/COMPoissonReg/index.html , or iii) resolve to the (somewhat dirty) solution of transforming the count data (e.g. by a log(x+1)) and then fit an lmer. The latter has the advantage that you can apply additional arbitrary transformation until the residuals are more or less normal.

**Comment by cdv04** [comment]
Dear Florian

I did what you suggested abour random effect. I used (1|Date) + (1|Site). The fact is that I have several measueremenst by Site but all the Site were not  visited in the same Date. I mean for the Date1, I could have several measurement for Site1 and Site2 for instance. And for Date2 I have  several measurements for Site3 and Site4, but no one for Site 1 and 2. etc..

But this new random structure didn't change anything concerning residuals.

I was playing with your package (reading again the vignette) and try the  refit=TRUE option in simulateResiduals function. And the obtained residuals seem to me very better. 

![better residuals](https://user-images.githubusercontent.com/5713124/36022218-8c015e3a-0d88-11e8-8c23-523f477cff5c.jpeg)

Do you know what happens ?

Finalley as you suggested  I've tried the lmer model with log(x+1). Residuals are normally distributed (shapiro test NS), and the results in terms of predictors significance are the same than those of my GLMM.

So it seems to me th'as my GLMM is  ok. What do you say ?

Thanks a lot for your kindly help.

Claire

**Comment by cdv04** [comment]
Hi Florian,

thank you so much for all your explanations. It helps me a lot. Concerning the dataset I have to analyse, it seems that some data were not homogebeous with other (something like opportunist transects observations).Removing these 16 data, I have no more problem of different results if my main predictive variable is log10 transform or not. Residuals are not perfect but they seem to me not so bad.
Thank you again for all your help.
