### ISSUE TITLE
Seeking Advice on Improving Model Fit for National Indicators Affecting Fishery Product Supply Index

### ISSUE THREAD

**Issue by riguelcontente** [florianhartig/DHARMa#452]
Hello everyone,

I am analyzing the effect of national indicators (GDP per capita, percentage of agricultural land, life expectancy) on the fishery product supply index (ISDI_final, an index ranging from 0 to approximately 100). I have a sample size of 3,047 observations. The best model I have obtained so far is as follows, with the accompanying fit results.  

best_model_3 <- glmmTMB(ISDI ~ ns(AgriL, df = 5) + ns(GDPPP, df = 6) + ns(LEAB, df = 6) + ns(GDPPP, df = 6) + (1 | Country),  family = tweedie(link = "log"). 

Summary:
Family: tweedie  ( log )
Formula:          ISDI_final ~ ns(AgriL, df = 5) + ns(LEAB, df = 6) + ns(GDPPP,      df = 6) + (1 | Country)
     AIC      BIC   logLik deviance df.resid 
  6277.9   6404.4  -3118.0   6235.9     3020 

Random effects:
Conditional model:
 Groups  Name        Variance Std.Dev.
 Country (Intercept) 0.0689   0.2625  
Number of obs: 3041, groups:  Country, 113

Dispersion parameter for tweedie family (): 0.0917 

Conditional model:
                   Estimate Std. Error z value Pr(>|z|)    
(Intercept)         1.45702    0.12523  11.635  < 2e-16 ***
ns(AgriL, df = 5)1 -0.10988    0.08832  -1.244  0.21349    
ns(AgriL, df = 5)2 -0.39193    0.09415  -4.163 3.14e-05 ***
ns(AgriL, df = 5)3 -0.20884    0.06784  -3.078  0.00208 ** 
ns(AgriL, df = 5)4 -0.73676    0.18849  -3.909 9.28e-05 ***
ns(AgriL, df = 5)5 -0.19494    0.08584  -2.271  0.02314 *  
ns(LEAB, df = 6)1   0.06345    0.05391   1.177  0.23921    
ns(LEAB, df = 6)2   0.30829    0.06199   4.973 6.59e-07 ***
ns(LEAB, df = 6)3   0.31416    0.06341   4.954 7.26e-07 ***
ns(LEAB, df = 6)4   0.13866    0.05662   2.449  0.01432 *  
ns(LEAB, df = 6)5   0.29394    0.11995   2.450  0.01427 *  
ns(LEAB, df = 6)6  -0.01449    0.06033  -0.240  0.81014    
ns(GDPPP, df = 6)1  0.17678    0.10383   1.703  0.08865 .  
ns(GDPPP, df = 6)2  0.18509    0.11032   1.678  0.09340 .  
ns(GDPPP, df = 6)3  0.18647    0.11401   1.636  0.10193    
ns(GDPPP, df = 6)4  0.43860    0.09831   4.462 8.14e-06 ***
ns(GDPPP, df = 6)5  0.27745    0.21982   1.262  0.20690    
ns(GDPPP, df = 6)6  0.91613    0.12032   7.614 2.66e-14 ***

This model is intended more to describe the relationship between ISDI and the predictors than to serve as a predictive model. Diagnostic analyses with DHARMa indicate some issues with model fit. Is there any procedure I could apply to improve the fit? I have tried several distribution families, and Tweedie has given the best results. Predictors are either transformed or centered to reduce the effect of data range.

Is there any particular concern regarding this model? Does it seem suitable for explaining the desired relationship pattern? Are there specific aspects I should pay attention to? Thank you in advance for your attention..

Best regards,
Riguel

![image](https://github.com/user-attachments/assets/8493e62c-4531-4430-a614-f0302b1d516b)
![image](https://github.com/user-attachments/assets/5c5c5c8f-7094-4a44-9231-99e966f63fd8)
![image](https://github.com/user-attachments/assets/25747aae-5246-4a53-a9c7-ed11aba05ddc)
![image](https://github.com/user-attachments/assets/c6a41d72-73dc-4f64-b748-6addddbbd32f)
![image](https://github.com/user-attachments/assets/b4e7d8f2-0090-44d8-9775-3276cdf5f147)
![image](https://github.com/user-attachments/assets/1c689f4a-c408-42e4-9066-4753ce8ff596)
![image](https://github.com/user-attachments/assets/596d3362-9115-4317-a82f-f93db9ab48cb)

**Comment by melina-leite** [comment]
Hi @riguelcontente,
I'm not sure if I can help you, but let's try:
- have you tried to model the dispersion parameter? From the residuals ~ predictors plots, it seems LEAB and GDPP can have some issues with heteroscedasticity
Also, if you have values from 0 to 100 (that could be transformed to 0-1), you could try the Beta distribution, and if you have zeros, you could try the beta zero-inflated.

Does it make sense?

**Comment by melina-leite** [comment]
Hi @riguelcontente, did you solve your problem? 
If so, I'll close this issue; if not, you can reopen it, and we keep discussing
