### ISSUE TITLE
move to native R parallel functions

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#52]
remove 
    
doParallel,
foreach,

to reduce dependencies

**Comment by florianhartig** [comment]
This was partly addressed in https://github.com/florianhartig/DHARMa/commit/de393edc47ae76bbf733f4b4b737078091b5edae

but the pure parallel version had a lot of export problems, so I changed back to foreach for now

**Comment by florianhartig** [comment]
@EttnerAndreas, could you have a look at this?

**Comment by florianhartig** [comment]
OK, it would be really good to get this thing done, and I think it's a nice contained project. Andreas, maybe you could give it a try, ideally in your fork?

https://github.com/florianhartig/DHARMa/pull/179/files

**Comment by EttnerAndreas** [comment]
alright, I will see what I can do. I will use my fork and let you know how it is going
