### ISSUE TITLE
testZeroInflation with k/n binomial data works correctly with weights, but not with two-column matrix response

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#55]
From a user:

You can specify the outcome in a binomial glmer model as k/n, with weights = n (in which case testZeroInflation() works correctly).  

But you can also specify the same outcome as cbind(k, n-k), with no weights in glmer, in which case the zerosObserved function within testZeroInflation() counts up the number of zeros in both the k vector and the n-k vector (survivors and deaths), which seems inappropriate to me (and gives a different answer).

**Comment by florianhartig** [comment]
Yes, that seems to be a bug, example

```
library(DHARMa)

testData = createData(sampleSize = 200, randomEffectVariance = 0, family = binomial(), binomialTrials = 2)

# glm help - For binomial and quasibinomial families the response can also be specified as a factor (when the first level denotes failure and all others success) or as a two-column matrix with the columns giving the numbers of successes and failures. 
# count successes
sum(testData$observedResponse1 == 0)
sum(testData$observedResponse0 == 0)

fittedModel <- glm(cbind(observedResponse1,observedResponse0)  ~ Environment1 , family = "binomial", data = testData)
summary(fittedModel)
simulationOutput <- simulateResiduals(fittedModel = fittedModel, n = 200)
testZeroInflation(simulationOutput)

# now with weights - glm help: Non-NULL weights can be used to indicate that different observations have different dispersions (with the values in weights being inversely proportional to the dispersions); or equivalently, when the elements of weights are positive integers w_i, that each response y_i is the mean of w_i unit-weight observations. For a binomial GLM prior weights are used to give the number of trials when the response is the proportion of successes: they would rarely be used for a Poisson GLM.

fittedModel <- glm(observedResponse1/2 ~ Environment1 , weights = rep(2, 200), family = "binomial", data = testData)
summary(fittedModel)
simulationOutput <- simulateResiduals(fittedModel = fittedModel, n = 200)
testZeroInflation(simulationOutput)
```

The bug is due to the fact that, until DHARMa 0.1.6, both k/n outputs were accidentally stored as observed data. I wasn't aware that this could create any problems (as it does here), but nevertheless I removed this behavior it with the recent changes related to adding glmmTMB support. 

Bottomline: this is already corrected in the latest development branch of DHARMa, which can be installed here https://github.com/florianhartig/DHARMa/issues/16

I'm just finalizing work on this branch, and will then merge back into the main development branch for the 0.1.7 release 

-> issue will be closed as soon as this is in the main development branch. 

Thanks for the report. And btw., if you are concerned about zero-inflation, then the recent addition with glmmTMB should be interesting to you, glmmTMB + DHARMa seems the perfect setup to model zero-inflation.

**Comment by courtiol** [comment]
Hi Florian,

there still seems to be a hickup with the binomial model (on the devel version 1.6.2):

```{r}
set.seed(1L)
y <- rbinom(100, size = 10, prob = 0.7)
table(y)
```
_y
3  4  5  6  7  8  9 10 
1  1 11 26 27 23  9  2_ 

```{r}
mod1 <- glm(cbind(y, 10-y) ~ 1, family = binomial())
testZeroInflation(simulateResiduals(mod1))
```

_DHARMa zero-inflation test via comparison to expected zeros with
simulation under H0 = fitted model_

_data:  simulateResiduals(mod1)
ratioObsExp = NaN, p-value < 2.2e-16
alternative hypothesis: more_

++

Alex

**Comment by florianhartig** [comment]
Yes, you're right, there's still something going wrong, thanks for reporting this!

I will have to look at this with more time. In the meantime, it seems that diagnosing the dispersion via the normal plots works reliably for both cases 

```
set.seed(1L)
y <- rbinom(100, size = 100, prob = 0.5)

mod1 <- glm(cbind(y, 100-y) ~ 1, family = binomial())
simulate(mod1)
res = simulateResiduals(mod1)
plot(res, asFactor = T)

y <- rbinom(100, size = 100, prob = 0.5)
mod1 <- glm(y/100 ~ 1, family = binomial(), weights = rep(100, length(y)))
res = simulateResiduals(mod1)
plot(res, asFactor = T)
```
