### ISSUE TITLE
DHARMa residual plots - no quantile lines in the residual plots

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#75]
Question from a user:

we are trying to model a binary response variable using a mixed effects logistic model fit with glmer. We have continuous and categorical predictors, and we have about 8000+ observations.

I have to say that I am completely puzzled by the shape of the residuals.

![image](https://user-images.githubusercontent.com/5457753/41624536-4a920e78-7416-11e8-81e4-96701d7836be.png)

 My understanding is that in the right plot, there should be 3 regression lines/curves representing the first, second, and third quartiles. In the plot that is attached, however, there seems to be only 2: one flat line at 0.5, and one dashed curve which is all over the place. Would you be able to provide some insight into what the dashed line is supposed to represent here?

**Comment by florianhartig** [comment]
Hi, this is expected behavior - the default of the plot function is to do the quantile regression for n <= 2000, and for larger datasets a nonparametric smoother, because the quantile regressions can take a long time to calculate. You can overwrite this if you want. Example

```
library(DHARMa)

testData = createData(sampleSize = 2200, family = poisson(), 
                      randomEffectVariance = 0, numGroups = 5)
fittedModel <- glm(observedResponse ~ Environment1, 
                   family = "poisson", data = testData)
simulationOutput <- simulateResiduals(fittedModel = fittedModel)

plot(simulationOutput) # default switches to quanreg = F for n > 2000 
plot(simulationOutput, quantreg = T) # overrule default
```

side note: with so many data points, and binomial, it would be useful to think about if you can group your data in some way, using the new recalculateResiduals() function in DHARMa 0.2.0

**Comment by jeychenne** [comment]
Thanks a lot for your answer. `quantreg=T` is the bit I was missing.
Regards,
Julien

**Comment by florianhartig** [comment]
Great. I'm keeping this open as reminder to update the help

**Comment by Robvh-git** [comment]
The KS test is significant, but the line QQ plot line looks very good. Am I correct to assume that due to the high number of samples, the KS test becomes overly sensitive, and one should then focus on the visuals?
