### ISSUE TITLE
Beta Mixed Effect Model - Interpretation Residual Plots and Tests

### ISSUE THREAD

**Issue by MelanieDou** [florianhartig/DHARMa#85]
Good afternoon,

I fitted a beta mixed effect model to a dataset of 10235 observations and then used your very useful DHARMa package to validate it. I got the following outcome
```
form_final <- fraction ~ logMigrantMW + logKow.calc. + ETOH_Equivalency + pH_numeric +  
    Crystallinity... + Hansen_Solubility_total_MPa + temp_K +  
    logTime.hrs + logKow.calc.:ETOH_Equivalency + temp_K:logTime.hrs +  
    (1 | Migrant_Name) + (1 | PolymerCAS.DisplayName) + (1 |  
    Food.NewName) + (1 | CitationID) + (1 | AnalMethod)
final_model <- glmmTMB(formula = form_final,data=database,family=beta_family(link="logit"),REML=T)
simulationOutput <- simulateResiduals(fittedModel = final_model, n = 250)
plot(simulationOutput)

testUniformity(simulationOutput)
	One-sample Kolmogorov-Smirnov test
data:  simulationOutput$scaledResiduals
D = 0.024578, p-value = 8.523e-06
alternative hypothesis: two-sided

testDispersion(simulationOutput)
DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

data:  simulationOutput
ratioObsSim = 0.49398, p-value < 2.2e-16
alternative hypothesis: two.sided
```
![plot_simulatedresiduals](https://user-images.githubusercontent.com/42808540/45748860-2e764d80-bc0a-11e8-926f-6599f57ba2d3.png)

Now my question: Am I really having a problem with overdispersion and non-uniformity? Or is it related to the comment on the vignette to the DHARMa package: "Hence, the p-value alone is not a good indicator of the extent to which your residuals deviate from assumptions. Specifically, if you have a lot of data points, residual diagnostics will nearly inevitably become significant, because having a perfectly fitting model is very unlikely. That, however, doesn't neccessarily mean that you need to change your model"?

I am looking forward to reading what you think,
Thank you in advance very much,
Mélanie

**Comment by florianhartig** [comment]
Hi Mélanie,

regarding the qq plot, I would say exactly this - it looks more or less fine, the significance is mostly because of the large number of observations. 

There seems to be a bit of a pattern in the res vs. predicted plot remaining though. Hard to say why, possibly a nonlinear effect of an important predictor? I'd do all the usual subplots to see if something shows up

- residual ~ predictors
- residuals ~ predictors | RE group
- REs ~ predictors

Best,
Florian

**Comment by MelanieDou** [comment]
Hi Florian,
Thank you very much for your quick answer! I will check the plots you suggest :)
Best,
Mélanie
