### ISSUE TITLE
Quasi-distributions in DHARMa

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#86]
Question from a user:

I am trying to diagnose a quasi-Poisson regression I've produced and am finding it a struggle. I came across your DHARMa package via Cross Validated and it looks very helpful - but of course it doesn't support quasi distributions.

I was wondering:

-     Are you planning to add support for quasi-distributions? (Or could I help you do that?)
-     Do you know of any similar packages that do support quasi-distributions?

**Comment by florianhartig** [comment]
As quasi-distributions have no clear underlying data-generating model (they are just a re-weighting of the Poisson / Binomial), it's not possible to simulate from them, so I don't see a possibility to support them in DHARMa.

To model overdispersed count data, I'd suggest to switch to a neg binom or use lme4 with an observation level random effect, which can be diagnosed with DHARMa, and which have a number of other advantages over the quasi distributions (AIC etc.)

**Comment by tomwwagstaff-product** [comment]
Thanks Florian,

I had (naively?) thought that - if I know the dispersion parameter in advance - I could just simulate a Poisson distribution and stretch out the residuals by the dispersion parameter to see what they should look like.

Looks like it's negative binomial for me...

**Comment by florianhartig** [comment]
hehe, but we can't stretch out integer values by a continuous variable ;)

Maybe this is useful https://stats.stackexchange.com/questions/157575/why-is-the-quasi-poisson-in-glm-not-treated-as-a-special-case-of-negative-binomi

I guess it would be possible to implement the various fixes / ways that people have suggested to create quasi-data in DHARMa, but as it stands I think a cleaner way is to only simulate from real distributions, as it is usually always possible to switch to one of these (at least if we have overdispersion, I admit underdispersion is a bit more complicated case).

Best,
F
