### ISSUE TITLE
No Inf values allowed for testing spatial autocorrelation

### ISSUE THREAD

**Issue by Z3tt** [florianhartig/DHARMa#92]
Hi Flo,

I am currently playing around with your nice package and might have figured out a problem when calculating spatial autocorrelation of the scaled residuals:

If you have a model that is fitted for several regions (IDs) over several time steps, these IDs will be redundant in the x and y coordinates or the distance matrix, respectively. Consequently, you will end up with some zeros which are not on the diagonal of the matrix. When the inverse matrix is calculated (as done by your  `testSpatialAutocorrelation()` function), the resulting values are of type `Inf`. Those on the diagonal are replaced but the others aren't which issues an error when calling `ape::Moran.I(..., alternative = "two.sided")`: 
```
Error in if (obs <= ei) 2 * pv else 2 * (1 - pv) : 
  missing value where TRUE/FALSE needed
```
I think the only way to deal with this is to replace them by 0 as well, i.e. adding the line `invDistMat[is.infinite(invDistMat)] <- 0 ` to your function. However, I am not sure if this is the right thing to do...?

Best,
Cédric

**Comment by Z3tt** [comment]
Read first, then code... After fixing it, I get the error message saying "use the recalculate Residuals function to aggregate residuals per location". Might be worth to get the error message also in the first place.

**Comment by florianhartig** [comment]
Yes, I know about the problem and what I suggest in the help is aggregating the data first (via the recalculateResiduals function) before calculating the spatial autocorrelation. 

I'm not sure if the distance zero solution is valid, because the inverse distance is not zero ... I guess putting a zero there means that this distance is not included in the Moran'I calculation, which doesn't seem entirely bad, but I'd like to hear a clear argument / proof first that this is valid before I accept the pull request. A rough

**Comment by florianhartig** [comment]
It's weird, you should have gotten the error message first ... in the code, the uniqueness of x values is checked before Moran's I is calculated

**Comment by Z3tt** [comment]
Hm, I definitely did not get this error but see what you mean - and it evaluates to TRUE as expected when I run it independently. Indeed strange. 

About the zero replacement: Yes, totally agree. I just cannot come up with any other solution at the moment and since it is valid for the diagonal, it might be as well for non-diagonal values. What is the argument for replacing the Inf values on the diagonal? It does not get used for the calculation anyway right? However, I am not expert on this and for me recalculating residuals on the group level makes more sense to me as I am not even sure if testing redundant IDs is correct from the stats perspective.

**Comment by florianhartig** [comment]
I'll remove the pull request. 

As I said, the solution to this problem is to create a unique grouping variable for each plot, and then run recalculateResiduals
