### ISSUE TITLE
Support for spaMM in DHARMa

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#95]
A user requested support for https://cran.r-project.org/web/packages/spaMM/index.html

**Perspective for this request**: spaMM seems to implement a suitable simulate function, so on a first glance, this seems possible without a major effort. I have to run further tests to see if all model classes can be simulated, and then integrate the package in DHARMa

**Interim solution** for users that, for some reason, have to urgently use DHARMa with this package: take your fitted model, simulate by hand, and then use createDHARMa (see help) - this will allow most options of the package to be run. See further comments on support of new packages in [here](https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA). Note that the vignette has some further comments / examples on creating custom simulation functions and reading them into DHARMa

**Comment by f-rousset** [comment]
Hi,
spaMM has a `simulate` function, but a few things are missing such as the trivial `family` extractor, for the spaMM fit objects to be compatible for call with the `simulateResiduals` function. I will look further into that issue (and the link above) in the coming hours/days.

F.

**Comment by florianhartig** [comment]
Until smaMM is integrated into DHARMa, here an example of Francois, with some modifications of me, to create simulations by hand and read them into DHARMa 

```
library(spaMM)

data("Loaloa") ## from spaMM package
loafit <- corrHLfit(cbind(npos,ntot-npos)~elev1+elev2+elev3+elev4+maxNDVI1+seNDVI
                    +Matern(1|longitude+latitude),
                    data=Loaloa[1:30,],family=binomial(),
                    init.corrHLfit=list(Nugget=0.1),ranFix=list(nu=0.5))

simsCond = simulate(nsim=250, loafit, type="residual") # I think that this is what I call a conditional simulat, i.e. simulations are conditinal on the fitted REs
simsUncond = simulate(nsim=250, loafit, type="marginal") # I think that this is what I call a unconditional simulation, i.e. random effects and glm distribution are re-siulated?

createDHARMa(simulatedResponse = sims, observedResponse = loafit$y,
             fittedPredictedResponse = predict(loafit, re.form=~0)[,1L], integer = T)
```

**Comment by florianhartig** [comment]
I have started to work on the spaMM integration. There are a few things, in particular a refit function, that I still need to implement, which is also the reason why the automatic tests still fail, but I think in principle the code in the branch

https://github.com/florianhartig/DHARMa/tree/0.2.0.3

is already usable (pre-alpha version). Happy to receive any feedback on this.  

@f-rousset - when integrating spaMM, I noticed a warning 

```
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘e1071’
```
which seems to originate from the fact that the dependency e1071 is not properly declared in spaMM.

**Comment by f-rousset** [comment]
@florianhartig 

Thanks for this, I will try to make a few tests soon.

I don't think that the warning implies that  the dependency e1071 is not properly declared in spaMM. Beyond the fact that spaMM passes CRAN checks, no function from e1071 is called if the test 
`do.call("require",list(package=pack, quietly = TRUE))`  (with pack="e1071") fails. It is this require() test itself which generates the warning, which I should probably suppress. But AFAIK, if(require(...)) is a valid way to test whether a package is available and does not implies per se that the tested dependency should be declared in spaMM.

**Comment by florianhartig** [comment]
This is practically done with https://github.com/florianhartig/DHARMa/pull/100, tagged 
in https://github.com/florianhartig/DHARMa/releases/tag/v0.2.0.3 

I'm sorting out a few smaller issues for the CRAN release.

**Comment by florianhartig** [comment]
DHARMa 0.2.1 which supports spaMM is now on CRAN. Francois, many thanks for your support!
