### ISSUE TITLE
Support for GLMMadaptive

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#96]
Request to add support for https://drizopoulos.github.io/GLMMadaptive/

**Perspective for this request**: GLMMadaptive seems to implement a suitable simulate function, so on a first glance, this seems possible without a major effort. I have to run further tests to see if this words and all necessary functions are supported (see [here](https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA)), and then integrate the package in DHARMa

**Interim solution** for users that, for some reason, have to urgently use DHARMa with this package: take your fitted model, simulate by hand, and then use createDHARMa (see help) - this will allow most options of the package to be run. Further comments / help on this [here](https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA) and in the vignette.

**Status**: there is a test version of DHARMa available that supports GLMMadaptive. Consider this alpha status. To use this, install the development version of GLMMadaptive and the 0.2.2.1 brach.

`devtools::install_github("drizopoulos/GLMMadaptive") devtools::install_github(repo = "florianhartig/DHARMa", subdir = "DHARMa", ref = "0.2.2.1")`

See details below.

**Comment by florianhartig** [comment]
Comment from Dimitris Rizopoulos about the behaviour of predict / simulate in GLMMadaptive

* indeed the predict() method allows for different type of predictions

   - "subject_specific" are conditional on the random effects

   - "mean_subject" are without the random effects, or more precisely 
put, for random effects equal to zero (hence also the name 
"mean_subject"); however, note that these are not marginal predictions 
because of the nonlinear link function used typically in GLMMs.

   - "marginal" are truly marginal predictions obtained by using 
marginalized coefficients for the predictors of the model.

* In the simulate() method indeed the only option up to a few minutes 
ago was to produce predictions conditional on the random effects, 
simulating each time new random effects values. However, on the current 
version on GitHub (GLMMadaptive_0.4-2) I added the option to also 
produce predictions for the "mean_subject", i.e.,

## S3 method for class 'MixMod'
simulate(object, nsim = 1, seed = NULL,
     type = c("subject_specific", "mean_subject"),
     acount_MLEs_var = FALSE, sim_fun = NULL,
     sandwich = FALSE, ...)

**Comment by drizopoulos** [comment]
Thanks!

The family() method is indeed implemented, but except from binomial() and poisson(), the other family objects in the package are not standard R family objects as those passed to glm(). Could you tell me what you exactly need to extract from the family() object.

nobs() is now implemented.

refit() I will need to think if I will implement this. I think this is doing the same as the update() generic?

Best,
Dimitris

**Comment by florianhartig** [comment]
Hi Dimitris,

sorry, my bad, family() was working with in development version. I had first installed the CRAN version, and then updated to the development version, but somehow it didn't update the package in my session. With a restarted R session it works now. I'm currently only using $family from the family() output. That should be fine. 

nobs() works, thanks!

about refit / update. Yes, in principle this can be done via update, and this is how I'm going to code it as well if you don't have a refit function. lme4 implemented the refit function mainly for speed reasons, which is useful, but I mainly prefer it because to use update(), I have to extract the data / model frame from the fitted model and the re-supply it to update(), which feels a bit unsafe / error-prone to me. But it's not a major issue. 

Best,
F

**Comment by florianhartig** [comment]
Hi @drizopoulos - I have a first version of DHARMa that works with GLMMadaptive. It's in https://github.com/florianhartig/DHARMa/tree/0.2.2.1, for testing if you want to.

To use this, install the development version of GLMMadaptive and the 0.2.2.1 brach.

`
devtools::install_github("drizopoulos/GLMMadaptive")
devtools::install_github(repo = "florianhartig/DHARMa", subdir = "DHARMa", ref = "0.2.2.1")
`

**Comment by drizopoulos** [comment]
Thanks! I’ll give it a try.

**Comment by florianhartig** [comment]
@drizopoulos  - I'm trying to implement a refit function - the main issue that I am still having is that GLMMadaptive does not return the random effects with model.frame(), and from what I see, they are not even stored in the fitted object?

**Comment by drizopoulos** [comment]
The empirical Bayes estimates of the random effects are stored in the fitted object, namely in the component `post_modes` and their variances in the component `post_vars`. They can also be extracted via the `ranef()` method.

**Comment by florianhartig** [comment]
sure, but for refitting (i.e. for using the update function), I would need to know the grouping variable for each data point, i.e. when I do ~ 1 | plot, I would need plot. 

The grouping variable is not returned by model.frame(), as it is in most other packages (e.g. lme4, glmmTMB, etc.).

I guess I could check for the data points with the same estimates, but this seems very hacky. Is the grouping variable stored somewhere, or do you simply throw it away after the model fitting?

**Comment by drizopoulos** [comment]
It is stored in the component `id` and its name in the component `id_name`. Hence, you could do something like `mframe_RE[[mod$id_name]] <- mod$id` to include it in the model.frame of the random effects design matrix.

**Comment by drizopoulos** [comment]
Hi Florian, it is not clear to me why you need to refit the model: Isn't the idea behind the simulated scaled residuals of **DHARMa** to simulate new responses from the fitted model and compare those to the observed data? Where is it needed to refit the model?

**Comment by florianhartig** [comment]
Hi, yes, the default mode is to do this, but I have an alternative method which is basically doing a parametric bootstrap, i.e. simulate new data, refit the model to new data, get a statistics about residuals. 

The latter allows you to run some tests that the former wouldn't be able to do (e.g. on the fitted likelihood), and my idea was also that the residuals might be more reliable in some cases, for example when an estimation method is biased, but the model is correct, the latter method should be less sensitive. 

That being said, I hardly use this in practice, and it's a lot of work maintaining this for the different packages, so I wonder if I should make a cut here, starting with GLMMadaptive, and only support standard simulations. 

Thanks for the help with the residuals anyway!

**Comment by WRobertLong** [comment]
Just wondering what the current status of this is ?

**Comment by florianhartig** [comment]
Hi Robert, and also @drizopoulos - yes, I'm sorry about this, I wanted to have this ready a long time ago. There was a branch where I started the implementation, but I hit a problem and then decided to first change the interface, which led to another problem, and then this got stuck. I have since then completely remodelled the way DHARMa interfaces to R packages, so the old branch probably won't merge, but on the bright side, it should be much easier to do the interface now. I will give this a go in the next weeks, I had this on my list anyway!

**Comment by rkirstentyler** [comment]
@florianhartig @drizopoulos Wondering about the current status of this, thanks!

**Comment by florianhartig** [comment]
I'll do it for the 0.3.4 release, it's on top of my priority list for this release

**Comment by florianhartig** [comment]
Hi, so the base implementation is there and merged to master, so you can get it via 

```
devtools::install_github(repo = "florianhartig/DHARMa", subdir = "DHARMa", 
dependencies = T, build_vignettes = T)
```

This is scheduled to go into the next DHARMa release. Beta tester welcome!

**Comment by drizopoulos** [comment]
Great! Thanks for including it as an option in your package.

**Comment by florianhartig** [comment]
@EttnerAndreas TODO:

- Run glmmAdaptive examples with simulated data and check if anything looks weird
- Run examples from glmmAdaptive help

Former two: add all examples above in a new file in Code/packageSupport/glmmAdaptive via a PR

- Check the unit tests in test/testthat/modelTypes.R

**Comment by florianhartig** [comment]
OK, I think I will close this for now, as nothing it seems to be working, or at least I have not heard otherwise, but again, @EttnerAndreas , would be good if you could try out a few examples just to check if anything weird happens.
